### ISSUE TITLE
uarg()

### ISSUE THREAD

**Issue by HarryCordewener** [pennmush/pennmush#1002]
Is this a command or @function?
Function

What will the permission restrictions be?
Same as u()

What will this do?
Allow u() arguments to be named

Can this be done in softcode?
Maybe? 

---

I mainly fear that this one might simply be impossible without some kind of huge change to the codebase. But I am putting this forward anyhow.

```
  uarg([<object>/]<attribute>[, <name0>, <arg0>[, ... , <name29>,<arg29>]]])

  uarg() evaluates <attribute> on <object> (or on the caller, if no <object>
  is given), and returns the result. Up to 30 <arg>s can be passed, available
  to the attribute as %0, %1, up to %9, and v(10) to v(29). This can be used 
  to create "user defined functions". The names are handed off to be used as
  a reference in r(name,args)
```

**Comment by HarryCordewener** [comment]
```
<Hardcode> Holland Mercutio says, "&myattr obj=add(%0,%1)"
<Hardcode> Holland Mercutio says, "&myattr_arg obj=add(r(DEX,args),r(ATHLETICS,args))"
<Hardcode> Holland Mercutio says, "u(myattr,<dexvalue>,<athleticsvalue>)"
<Hardcode> Holland Mercutio says, "uarg(myattr_arg,DEX,<dexvalue>,ATHLETICS,<athleticsvalue>)"
<Hardcode> Holland Mercutio says, "Do you see what I am aiming for now, Mike?"
<Hardcode> Holland Mercutio says, "More work for the coder, but basically making it easier to look at a function-attribute and knowing what it does. Making for more self-documenting code."
<Hardcode> [({<>})] Mike says, "Ahh. Yes, that would be quite trivial to do."
<Hardcode> Holland Mercutio says, "I think that'd be an amazing addition."
```

**Comment by HarryCordewener** [comment]
P.S. 
People may want the same for eval().
evalargs() ?

**Comment by talvo** [comment]
The entire point of eval() is that it doesn't modify the stack, so that wouldn't make much sense.

**Comment by MrWigggles** [comment]
If its going to be applied to a lot of different functions, which, doesnt seem like a bad thing, wouldn it be better to change how it passes on arguments then to have a separate function?

u(fooattr, argName:ArgValue, AgName2:ArgValue)

I suppose that having a new new suite of functions would defiantly preserve backwards comp, but I think its just very close to bloating up the functions more.

Like, myself personally, I'd be annoyed if if named args q-regs had to be a different functions from the other q-reg functions.

**Comment by talvo** [comment]
The problem is that that would break backwards compatability with -everything-. Practically every single bit of code in the wild would break. That is not really acceptable.

**Comment by HarryCordewener** [comment]
Yeah, thus the suggestion of a separate function name for this type of behavior.

**Comment by talvo** [comment]
I'm inclined to add a function for naming arguments in the current scope than for u()ing an attribute with named arguments. ie:

&foo me=nameargs(0,jeff,1,rodney,2,bill)[pemit(%#,r(bill,args))]
u(me/foo,this,that,the other)

**Comment by MrWigggles** [comment]
How is that different then setq()?

**Comment by HarryCordewener** [comment]
While I know that's different from setq(), the methodology just doesn't feel right. But more-so, it doesn't help readability much. In fact, I almost feel like that is worse than using setq() to drag arguments from one place to the other.

**Comment by captdeaf** [comment]
This really is the point of Q-registers, imho. You might like letq()

&myattr foo=add(%q<dex>,%q<athletics>)
&myattr_arg foo=letq(dex,3,str,-2,con,1,athletics,8,...,u(myattr))

**Comment by HarryCordewener** [comment]
Only the lifetime/scope of an argument is completely different from a register. It also doesn't require the use of ulocal() to stop it from getting clobbered, etc.

**Comment by talvo** [comment]
Consensus seems to be that this doesn't provide enough benefit to be worthwhile, especially since we'd need to add special variants of so many functions and commands to make it more widespread.

**Comment by HarryCordewener** [comment]
For the sake of those who seek uarg() in the future:

Thank you Talvo for tossing this at me: (To be placed into funlocal.c - please notice the seperate code pieces, and don't place them within EXAMPLE space.)

UARG()
```

/* ARGSUSED */
FUNCTION(fun_uarg)
{
  char rbuff[BUFFER_LEN];
  ufun_attrib ufun;
  int flags = UFUN_OBJECT;
  PE_REGS *pe_regs;
  int i, j;

  if (!(nargs % 2)) {
    safe_format(buff, bp, T("#-1 FUNCTION (%s) EXPECTS AN ODD NUMBER OF ARGUMENTS"), called_as);
    return;
  }

  if (!fetch_ufun_attrib(args[0], executor, &ufun, flags)) {
    safe_str(T(ufun.errmess), buff, bp);
    return;
  }

  pe_regs = pe_regs_create(PE_REGS_ARG, "fun_ufun");
  for (i = 1, j = 0; i < nargs; i += 2, j++) {
    pe_regs_setenv_nocopy(pe_regs, j, args[i+1]);
    pe_regs_set(pe_regs, PE_REGS_ARG | PE_REGS_NOCOPY, args[i], args[i+1]);
  }

  call_ufun(&ufun, rbuff, executor, enactor, pe_info, pe_regs);

  pe_regs_free(pe_regs);

  safe_str(rbuff, buff, bp);

  return;
}
```

Put UARG into the Functions list:
```
void
local_functions(void)
{
  function_add("UARG", local_fun_uarg, 1, (2* MAX_STACK_ARGS)+1, FN_REG);
}
```
