### ISSUE TITLE
convsecs() and convtime()

### ISSUE THREAD

**Issue by KimikoMuffin** [pennmush/pennmush#1010]
This applies to both convsecs()/convtime() and convutcsecs()/convutctime().

`convtime(Jan 01 00:00:00 1969)` returns -31518000, a valid timestamp. However, `convsecs(-3151800)` returns `#-1 ARGUMENT MUST BE POSITIVE INTEGER`; the two functions are not circular. You get similar results for values after [2038](http://en.wikipedia.org/wiki/Year_2038_problem); `convutctime(Jul 28 00:00:00 2061)` returns 2889752400, `convutcsecs(2889752400)` returns `#-1 ARGUMENT MUST BE POSITIVE INTEGER`.

Furthermore, `convtime(Invalid Timestamp Value)` returns `-1`. Not only are convsecs() and convtime() inconsistent in their return values, convtime() with an invalid argument returns a result which is indistinguishable from a valid value.

I propose two things:

1. Allow convsecs() and convutcsecs() to take larger integer values and negative integer values.
2. Either change convtime() to return some sort of `#-1` error on an invalid value (which I'm aware would break existing softcode), add an `istime()` function to detect whether a given value is a valid time format according to the hardcoded settings (not fully possible in softcode), or both.

**Comment by talvo** [comment]
While backwards compatability is certainly important, I think this is a good example of when to break it.

**Comment by KimikoMuffin** [comment]
... "Volund"?

**Comment by talvo** [comment]
Woops, sorry! Been blaming him for so much lately it was a force of habit ;) Will fix.

**Comment by mrsenile** [comment]
Bad Mike... bad... so... when is Penn going to join the 21st century and do 64 bit time for their convsecs/convtime? :)
