### ISSUE TITLE
Amend Help File for iter or maybe action lists?

### ISSUE THREAD

**Issue by MrWigggles** [pennmush/pennmush#1013]
Very recently Cheetah wrote a snippet of code, that did a wonderful demonstrate of what ## sub does, and I think it'd be beneficial to have that snippet in.

[Sat Aug 08 19:02:13 2015] <Softcode> @cemit/noisy Cheetah says, "Do note funny things like.. iter(\(1\,1\),add##)

**Comment by MrWigggles** [comment]
Inside the helpfile for just the action list or for iter and @dol ?

**Comment by talvo** [comment]
Seems reasonable.

**Comment by dol** [comment]
Thx for mentioning me. In love @dol :tada: :smile:
