### ISSUE TITLE
@hook/ignore: q-registers & not passing arguments

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1014]
Currently, if you use a @hook/ignore function in combination with a command. E.g. Hooking look to add additional virtual items, the registers between the function used in @hook/ignore and the softcode command that is called instead do not share registers, causing you to potentially have to parse the same code twice, once to return 0 to the @hook, and once for the actual softcode command that takes over.

@hook/ignore also does not pass arguments to the called function, requiring pulling it out of %u.

**Comment by talvo** [comment]
https://github.com/pennmush/pennmush/pull/1016 Pull request pending approval.

**Comment by talvo** [comment]
Duplicate of #924
