### ISSUE TITLE
@password should flash you the new password

### ISSUE THREAD

**Issue by MrWigggles** [pennmush/pennmush#1017]
When setting a new \@password on yourself, when it sets the new password, it should then show you the password you just set.

**Comment by HarryCordewener** [comment]
This seems like a bad idea. Just use local echo if you wanna know what you typed a second ago. And if you don't have echo running, and don't want people reading over your shoulder knowing the password that you probably use for all the other sites you visit...

You probably don't want this either.

**Comment by tkrajcar** [comment]
:-1: on this as well, seems like it's 100% trouble waiting to happen with logs getting shared, etc, and the upside is not worth it..

**Comment by talvo** [comment]
Sorry, Wigs, the mob has spoken.
