### ISSUE TITLE
Request: getdate.template

### ISSUE THREAD

**Issue by volundmush** [pennmush/pennmush#1020]
Why not use this version? This is what Mercutio made for his SceneSys and it's required for mine to work. It doesn't break any backwards Compatability!

https://github.com/volundmush/mushcode/blob/master/Version1/scenesys/getdate.template

**Comment by HarryCordewener** [comment]
The main reason this template was adjusted against the PennMUSH template is to allow more of the common date formats. But far more importantly, it includes the DateTime format that MySQL uses.

**Comment by talvo** [comment]
Added some, but not the ambiguous ones that use numeric 'month day'.
