### ISSUE TITLE
Feature Request: valid(lockstring,)

### ISSUE THREAD

**Issue by volundmush** [pennmush/pennmush#1025]
Thing I want to be able to do: valid(lockstring,FLAG^WIZARD)
Or something more complicated. You get the idea!

Not sure whether it should be called lockstring or not. Also this isn't critical, I can work around it.

It would be nice to have though.

**Comment by talvo** [comment]
This is easy enough to do in other ways, but also easy enough to add that it might be worth doing anyway.

**Comment by talvo** [comment]
Done. (I keep forgetting to auto-close the tickets from the commit message.)
