### ISSUE TITLE
Help file formatting

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1030]
The helpfiles are hard-wrapped to 78 characters. In this day and age, the chances of anyone connecting via a client that does no wrapping whatsoever are slim-to-none (and everything they see/hear will be borked anyway, if they do, already rendering things pretty much unplayable). The majority of players also connect from clients with much larger displays, too, in which case the helpfiles being hard-wrapped as such a relatively small size is annoying.

I hearby vote we remove the manual wrapping, and am happy to volunteer to do it if noone has complaints.

**Comment by HarryCordewener** [comment]
I vote for this.

**Comment by tkrajcar** [comment]
:+1:

**Comment by talvo** [comment]
Started in branch https://github.com/pennmush/pennmush/tree/unwrapped-helpfiles . This is slightly monotonous work, so if anyone wants to check out a copy and help with some of it, it would be greatly appreciated.
