### ISSUE TITLE
Stop the killing

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1033]
The "kill" and "slay" commands are ridiculously easy to softcode if you want them, but let's be honest, noone does; they have no real use on a MUSH and are basically always disabled, if people even remember they exist. Let's get rid of them.

**Comment by HarryCordewener** [comment]
I can't give this enough 'LIKE' or 'THUMB UP' or 'YES'es...

**Comment by HarryCordewener** [comment]
Or at least disable by default.

**Comment by MrWigggles** [comment]
Lets.

**Comment by tkrajcar** [comment]
Got most of this done. As part of doing this I'd like to propose that we remove the `HAVEN` flag. Without its kill-preventing behavior, it would only be settable on players and is functionally nearly-equivalent to just doing `@lock/page me==me`. Please let me know if anyone objects strongly.

**Comment by tkrajcar** [comment]
@grapenut noted that the HAVEN flag also is connected to the `@haven` attribute, which is still very much needed. If HAVEN is removed, I suggest this should be renamed to `@pagefail` going forward (with support for the `@haven` attr for legacy code/DBs, of course), so I'm adding that to my proposed course of action. Comments welcome.

**Comment by MrWigggles** [comment]
Didnt havent also stop you from being \@tel'ed?

**Comment by grapenut** [comment]
@tkrajcar has my complete support in this endeavor.

**Comment by tkrajcar** [comment]
@MrWigggles Believe you're thinking of HEAVY, which still exists.

**Comment by grapenut** [comment]
That's FIXED for players

**Comment by MrWigggles** [comment]
I +1 for turning haven into @pagefail that has utility.

**Comment by tkrajcar** [comment]
So, it seems there's a [```PAGE_LOCK`FAILURE```](https://github.com/pennmush/pennmush/blob/master/game/txt/hlp/penncmd.hlp#L3384) attribute that's already used by the page code, which removes the need for `@haven`/`@pagefail`/whatever altogether. I had no idea this existed, and I'm not wild about the name, but there you go. :)

**Comment by talvo** [comment]
I would suggest keeping `@haven` (even if we rename it) for normal people to use.

**Comment by tkrajcar** [comment]
Sounds good to me @talvo. Got my first crack at this PRed.

**Comment by grapenut** [comment]
I don't think you need to keep the HAVEN flag. I think Mike was referring to the @HAVEN attribute. Could make the attribute an alias for the one with the crappy name, then have hardcode check the HAVEN attribute if the other one isn't present..
