### ISSUE TITLE
Remove speakpenn()

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1034]
Or, more accurately, make it and speak() behave identically, and then keep it as a backwards-compatible alias only.

The only difference between the two is that is that, in speak(), ': foo' behaves as ';foo' like in TinyMUSH, and in speakpenn() it behaves like ':foo'. The default speak() behaviour is not compatible with anything else in Penn (there's no way to make our 'pose' command behave like that), and I really don't see the point in keeping it like that.

(We could make "speaktiny()" to keep the behaviour available; I don't see any point in that, either.)

**Comment by HarryCordewener** [comment]
I thought it had to do with the order of the arguments?

**Comment by talvo** [comment]
I think you're thinking of the trim() stuff.

**Comment by HarryCordewener** [comment]
I must be.

**Comment by aiviru** [comment]
Duplicating the weird Tiny syntax always struck me as a very odd choice. If you're used to Penn-isms it just adds another PHP-ish 'no you don't use the function you think, you use a different one' kind of gotcha.

I'm all for tossing it.
