### ISSUE TITLE
Realities/Realms from MUX

### ISSUE THREAD

**Issue by g33kcub** [pennmush/pennmush#1036]
What are the odds of getting either the Realities or Realmed Flags (Like MUX has both) added to Penn?

**Comment by talvo** [comment]
It's already possible to do, although it requires some hardcoding on your part currently, and as far as I know there aren't really any good examples of it any more. If you let me know exactly what features you want, though, I'll try and write it up for you and then include it as an example.

**Comment by g33kcub** [comment]
I'm looking for OBFuscate code, Shadow(Umbra), Fae sight

Those are the main ones.

**Comment by talvo** [comment]
I'm afraid I know nothing about it, so you'll need to tell me/link to how it should work.

**Comment by g33kcub** [comment]
This is the realities entry from MUX (Which is like Rhost)

Example 2: A WoD setup
The reality levels will be defined like this:
reality_level Real 1 reality_level Obf1 2 reality_level Obf2 4 reality_level Obf3 8 OBFDESC reality_level Obf4 16 OBFDESC reality_level Obf5 32 OBFDESC reality_level Umbra 64 UMBRADESC reality_level Fae 128 FAEDESC reality_level Shadow 256 SHADOWDESC reality_level All 511
Five levels of Obfuscation, Umbra, Dreaming, Wraiths. 'All' is a handy replacement for all levels, useful for wizards and wizobjects that should be visible on all levels. Also useful when you want to set an object's levels to something without knowing what he had before. @rxlevel #276=!All Real !All will clear all levels, then the object will gain the Real level. There is more than one Obfuscation level because of the relation between Auspex and Obfuscation. A vampire with Obfuscate 2, should not be visible by one with Auspex 1. However one with Auspex 3 should see another vampire with Obfuscate 1, 2 /or/ 3. Obfuscated players can move if they have Obf > 1. Umbral and Shadow players should also be able to see most of the exits. So the exits at creation should have default levels of Real + Obf2 + Obf3 + Obf4 + Obf5 + Umbra + Shadow = 1 + 4 + 8 + 16 + 32 + 64 + 256 = 381
   def_exit_rx 381
   def_exit_tx 381
Obf1 is not included since an Obfuscated vampire should not be able to move if it only has Obf1. Therefore they won't see the exits. If you want them to be able to see the exits, but not to use them, change the default Tx of the exits:
   def_exit_rx 381
   def_exit_tx 383
Joe the Mortal will have an RxLevel: Real and a TxLevel: Real Jack the Malk, who likes to walk around Obfuscated and has Obfuscate 2 will have an RxLevel: Real (he sees what the mortals see) but a TxLevel: Obf2 Jimmy the Nossie, who is using the Mask and has Obfuscate 4, but doesn't try to make himself invisible will have an RxLevel: Real (as Jack) and a TxLevel: Real Obf4. He will also set his @desc to what the mortals see and &OBFDESC to his real slimy desc. Simply put, he will be visible to mortals, but not with his real desc. Aldrin the Gangrel, has Auspex 4 and activates it. Therefore, his TxLevel will still be Real, but RxLevel: Real Obf1 Obf2 Obf3 Obf4 (all of them). So he can see Joe, Jack and Jimmy's both descs. Joe, on the other hand, won't see Jack at all. He will still see Jimmy, but only Jimmy's @desc, not the OBFDESC.
Frida the Fae... will have RxLevel: Real Fae and TxLevel: Real Fae. @desc set to the mundane desc, &FAEDESC set to the Chimerical desc. Emily the Enchanted will have an RxLevel: Real Fae, but the TxLevel: Real. No &FAEDESC on her, although she'll be able to see it the one on Frida. Gil the Garou, while travelling through the Umbra, will have RxLevel: Umbra and TxLevel: Umbra. &UMBRADESC is his friend. He won't see mortals or other characters who are not in the Umbra. Barbie the Bastet, who's only peeking in the Umbra, without going there, will have RxLevel: Umbra, TxLevel: Real. Dangerous position since she can't see the things that see her. Deanna the Drake, who activates her spirit vision, will have RxLevel: Real Umbra and TxLevel: Real. She will see characters in Umbra and real world at the same time and perceive the desc appropriate to the realm the ohter character is in. Wanda the Wraith: RxLevel: Real Shadow, TxLevel: Shadow. Her @desc would be empty, but the &SHADOWDESC should be set. Marie the Mortal+ Medium: RxLevel: Real Shadow, TxLevel: Real
Global code objects that all characters should be able to use: RxLevel: All, TxLevel: All

**Comment by mrsenile** [comment]
Ok, here's a bit of background on how Realities work.

There's two flows.  TXLevel and RXlevel.  Think like networking.

If you belong in the TXLevel, you can transmit to that reality.  If you belong to the RXLevel you can receive from that reality.  You can belong to either, or, or neither at any given time.  There is also lock constraints that can offer overrides based on parsing (A bit like your @Lock/interact) that can either override that behavior or be used as an additional check (depending on how it's configured).

You can belong to upwards to 31 realities at any given time, in either/or catagories of RX and TX.

**Comment by mrsenile** [comment]
Oh, and the realities cover all possible situations.

^listens/@listens, $commands, master-room events, entering/leaving, connecting/disconnecting, pretty much it sandboxes you based on what realities you belong in.

**Comment by talvo** [comment]
OK... Rhost and MUX do it to a much deeper level than is possible using the hooks in local.c, and one that I wouldn't really want in vanilla Penn. The local.c hooks would take you a fair way (it would affect what you can see and hear, and what you can match in most cases), but it wouldn't handle things like changing `@desc`s (you'd need to handle that in softcode, possibly with an `@descformat` on ancestors or something). It also wouldn't prevent $-command matching; you'd need to use `@lock`s if you cared about that (though ^listens should be affected, since that comes under what can hear you).

**Comment by g33kcub** [comment]
Ok. I will have to rig up some kind of object system to make them happen then.

**Comment by shawnw** [comment]
I don't see this ever happening in Penn unless somebody with motivation does it and submits a pull request.
