### ISSUE TITLE
Get rid of the Keepalive flag.

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1039]
Any client with even minimal telnet support can handle receiving a telnet nop, so having a flag for it is pretty pointless; we may as well just send the nop to every telnet-enabled client, instead of making people opt in for it.

**Comment by annelions** [comment]
If everyone gets it, removing the flag itself is fine by me. IDLE by itself isn't always enough to keep a connection open.

**Comment by Sketch** [comment]
Downvoting this one. Sending those NOPs can actually tax high-latency and laggy connections (like mobile phones and dial-up) which aren't uncommon.

**Comment by HarryCordewener** [comment]
I downvote this, because I've seen clients that can't handle NOPs - and it just gets spammy.

**Comment by talvo** [comment]
Closing, then. Though any client that claims to do telnet support and can't handle a nop sucks. Just sayin'. ;)

(Same for any connection that can't handle 2 extra bytes once per minute.;)

**Comment by HarryCordewener** [comment]
Agreed :)
