### ISSUE TITLE
Add unit tests for json() softcode function

### ISSUE THREAD

**Issue by Sketch** [pennmush/pennmush#1040]
A couple examples. Doesn't need exhaustive testing, and there are of course cases that SHOULD be left ambiguous.

json(boolean,adsfa) --> #-1 INVALID VALUE
json(array,) --> [](without Tiny null_eq_zero. Behavior is contradictory but necessary if null_eq_zero is true)
json(array,1 2 3) --> [1 2 3]
json(object,key,json(array,1 2 3)) --> {"key": [1 2 3]}
(One of the few cases where nesting might be pretty good in testing.)

**Comment by talvo** [comment]
Some added in https://github.com/pennmush/pennmush/commit/863d609312662ca862b0c1fc99167b5f964303cf, still need to add some for json_map().

**Comment by shawnw** [comment]
Things to be tested in testjson.pl:

- [x] json(null)

- [x] json(boolean)

- [x]  json(string)

- [x] json(number)

- [x] json(array)

- [x] json(object)

- [ ] json_query type

- [ ] json_query size

- [ ] json_query exists

- [ ] json_query get

- [ ] json_query unescape

- [x] json_query patch

- [ ] json_map()

- [ ] isjson() (Uses sqlite3 code which is well tested)
