### ISSUE TITLE
Unable to contribute to pennmush

### ISSUE THREAD

**Issue by mcgiwer** [pennmush/pennmush#1042]
I cannot contribute to pennmush - I'm getting the 403 error. Please fix it asap

**Comment by tkrajcar** [comment]
Hi @mcgiwer, I'm not sure what "the 403 error" is. We welcome contributions as pull requests. If you have a contribution you'd like to submit, you'll need to fork the pennmush/pennmush repo, push your changes onto a branch, and open a pull request. [This guide](https://gun.io/blog/how-to-github-fork-branch-and-pull-request/) describes the process. If there's something else you're trying to do, feel free to re-open with more information.

**Comment by talvo** [comment]
What exactly were you trying to do? Basically all contributions would go through github now, but since you opened a ticket here successfully I assume you meant something else. The only thing I can think of off the top of my head might be the old translation site, which has been down for quite some time (though even those can be done via tickets or pull requests on github now).

**Comment by mcgiwer** [comment]
@tkrajcar Error 403 means exactly: "Forbidden", with shows in repositories if some users for some reason don't have write write permission

@talvo I tryed upload the generated API documentation, update the .gitignore (it was ignoring some source code with made the compilation trow out warnings), etc.

**Comment by talvo** [comment]
Ahh, I see. Yeah, you can't commit directly to the repository, as @tkrajcar said you'll need to fork and then submit a pull request.

**Comment by mcgiwer** [comment]
@talvo I tryed to fork, but got same error. It seem it's something with the repo that don't let me commit. It would be nice if you add me to contributors and set that anyone in this group has write permission to whole repoitory

**Comment by HarryCordewener** [comment]
@mcgiwer, This might help you understand why we do not open it to direct commits: 
https://guides.github.com/introduction/flow/

**Comment by tkrajcar** [comment]
@mcgiwer You need to click the 'fork' button at the top right of this or any other page in the repo, then select your personal account 'mcgiwer' as the destination. If that doesn't work for you, that's a Github problem and something you need to contact them about, not anything we have control over.
