### ISSUE TITLE
Errors while executing `make`

### ISSUE THREAD

**Issue by mcgiwer** [pennmush/pennmush#1044]
Wkile trying to compile the project by using the `make` command, I get following errors:

bsd.o bsd.c
In file included from bsd.c:96:0:
../hdrs/mysocket.h:53:19: error: field ‘addr’ has incomplete type
   struct sockaddr addr;         /**< A sockaddr structure */
                   ^
bsd.c: In function ‘got_new_connection’:
bsd.c:933:5: warning: implicit declaration of function ‘accept’ [-Wimplicit-function-declaration]
     newsock = accept(sock, (struct sockaddr *) &addr, &addr_len);
     ^
bsd.c: In function ‘shovechars’:
bsd.c:987:30: error: ‘SOCK_STREAM’ undeclared (first use in this function)
     sock = make_socket(port, SOCK_STREAM, NULL, NULL, MUSH_IP_ADDR);
                              ^
bsd.c:987:30: note: each undeclared identifier is reported only once for each function it appears in
bsd.c: In function ‘new_connection’:
bsd.c:1399:7: warning: implicit declaration of function ‘shutdown’ [-Wimplicit-function-declaration]
       shutdown(newsock, 2);
       ^
bsd.c: In function ‘network_send’:
bsd.c:2083:5: warning: implicit declaration of function ‘send’ [-Wimplicit-function-declaration]
     int cnt = send(d->descriptor, cur->start, cur->nchars, 0);
     ^
bsd.c: In function ‘telnet_naws_sb’:
bsd.c:2261:3: warning: implicit declaration of function ‘ntohs’ [-Wimplicit-function-declaration]
   d->width = ntohs(raw.s);
   ^
bsd.c: In function ‘process_input’:
bsd.c:3532:5: warning: implicit declaration of function ‘recv’ [-Wimplicit-function-declaration]
     got = recv(d->descriptor, tbuf1, sizeof tbuf1, 0);
     ^
bsd.c: In function ‘load_reboot_db’:
bsd.c:7012:38: error: ‘SOCK_STREAM’ undeclared (first use in this function)
       sslsock = make_socket(SSLPORT, SOCK_STREAM, NULL, NULL, SSL_IP_ADDR);
                                      ^
make[1]: *** [bsd.o] Error 1

With unallow me to complete the compilation

**Comment by grapenut** [comment]
sys/types.h and sys/socket.h appear to be not found. Did the configure script report any errors? Check config.h for I_SYS_* variables

grep I_SYS config.h

Make sure all of the I_SYS_* are defined.

**Comment by mcgiwer** [comment]
after downloading and extracting the archive downloaded from this repo, I executed following commands:

$ ./configure -  Completed without errors
$ make update
$ make - has trown out mentioned in previous post errors

Note: I have the CFLAGS set to (without quota marks) "-O3"

**Comment by talvo** [comment]
Check your pennmush/config.h file, see if HAVE_SYS_SOCKET_H is defined or if the #define for it is commented out. Looks like you either don't have some things that Penn needs installed, or installed in a place it's not finding it. What's the OS? (Feel free to attach your config.h if you like.)

**Comment by mcgiwer** [comment]
@talvo I didn't edited any file yet. It's a "fresh" download from the repo.

Actually I use Ubuntu 14.04 (32-bit), but plan to move as soon as possible to 14.10 (64-bit). For now I won't move to 15 because it's still not too stable

**Comment by talvo** [comment]
config.h is generated when you run configure, based on what PennMUSH can find on your system, that's why we're asking for the info there.

**Comment by mcgiwer** [comment]
@talvo I agree, but it's generated from the template file called 'config.h.in'. If there is not defined or is defined incorrectly then the generated 'config.h' it won't appear as well

**Comment by shawnw** [comment]
Yeah, put up your config.h on pastebin or somewhere and share with us. Given it's Ubuntu, I'm guessing there's some -dev package that should be installed that isn't.

**Comment by mcgiwer** [comment]
config.h.in: http://pastebin.com/TqXpzWrC
config.h: http://pastebin.com/fCDgzqyB

**Comment by talvo** [comment]
I am genuinely unsure what the issue is, off the top of my head, then; it seems like all the necessary header files are being found by configure. Try a `sudo apt-get install build-essential` and see if it adds something that resolves your problem?

**Comment by talvo** [comment]
Has this been resolved, or are you still having trouble?

**Comment by mcgiwer** [comment]
I already have the latest build-essential and I still getting the error message(s) while trying to make it

**Comment by mrsenile** [comment]
Make sure you have the right dev packages installed.  They would end in -devel in ubuntu (I believe).

Also, I believe you need the following libraries in your MORELIBS/LIBS for your Makefile:

-lresolv -lsocket -lnsl

**Comment by mcgiwer** [comment]
may I suggest that:

* all requirment libs were included as bundle
* in the configure, configure.in and Makefile.in files add method with check the current OS and architecture, set propper params in the files and include propper libs

The above would solve the issues

**Comment by talvo** [comment]
That is generally the case for configure, @mcgiwer (that is the entire point of it, really); however, lots of people run on Ubuntu and we've never seen this issue before, which is why we're taking some educated guesses at what might resolve it.

Bundling libraries with Penn isn't really practical or desirable, though; the vast majority of people would rather install them themselves from their package manager (and usually already have them). If we included everything, as well as Penn becoming a few hundred times bigger, we'd spend all our lives reading licenses for stuff to see if we could bundle it, trying to keep it all up to date, etc. That being said, if we discover a library you're missing that resolves the problem you're having, we'll certainly document the fact for the future.

**Comment by grapenut** [comment]
Look at the few lines just prior to the error you posted above. You are looking for the command given on the command-line to compile bsd.c. It should say somewhere "-I/usr/include" and if it does not, that is the problem. If it does have that option, then look in the /usr/include/sys directory for the types.h and socket.h files. If you don't have these files, then you don't have the libc dev packages installed.

**Comment by mcgiwer** [comment]
@talvo My proposal (the variable part) was meant to set the default patches of includes and libraries as default ones in case of badly detecting of some libs and includes (with occurs very often in many configure and Makefile files), not only in pennmush.

__ The suggested pathes for mentioned above for Ubuntu: __

__ includes __: /usr/include
__ libs __: /lib /lib64 (*) /usr/lib /usr/lib64 (*) /usr/local/lib /usr/local/lib64 (*) /var/lib /var/lib64 (*)

__ *Note*: __  Entries marked with (*) should be included only for 64-bit systems

**Comment by mcgiwer** [comment]
why does the markdown don't work?

**Comment by grapenut** [comment]
The problem is pretty simple. It's not finding the libc headers, which are basic system files (and definitely not something that could or should be packaged with anything). You should have a line that tells the compiler to look in /usr/include, and you should have some files like sys/types.h, sys/socket.h, arpa/inet.h, etc. under /usr/include. This is the error that was reported. All of the functions and constants that it couldn't find are defined in those files.

**Comment by mcgiwer** [comment]
@grapenut I have the mentioned by you files, but it seem that by compiling attempt, somehow the scripts aren't properly detecting the include and/or libs pathes. it's kinda annoying to put the pathes as parameter when compiling any new version of penn

**Comment by talvo** [comment]
The `#define`s in config.h suggest that the files -are- being found, so it's quite strange that the locations they're being found in are, apparantly, not being checked. Have you tried any of the suggestions given manually with any success, and if so, which? Also, please attach your config.log file so we can see exactly what configure found where.

**Comment by grapenut** [comment]
Look at the Makefile, does it have -I/usr/include on the CCFLAGS line?

**Comment by talvo** [comment]
I'm guessing from the fact you've posted other tickets with a working copy of Penn that you resolved this, @mcgiwer ?

**Comment by mcgiwer** [comment]
sorry for nit replying... I lost intenet acces due moving to new home. I need to download the newest Penn version and check it

**Comment by talvo** [comment]
Resolved.
