### ISSUE TITLE
Fix --without-openssl in configure

### ISSUE THREAD

**Issue by Sketch** [pennmush/pennmush#1047]
Trying to do './configure --without-openssl' results in the error message "configure: error: Invalid --with-openssl value". It should either be possible to compile without SSL, or...not!

**Comment by talvo** [comment]
OpenSSL is required these days.

**Comment by Sketch** [comment]
Then my recommendation is removing --without-openssl. :)

**Comment by shawnw** [comment]
Unfortunately, that's hard to do with the way autoconf and the macros used in the OpenSSL test work.  You're lucky it complains in the configure script and not when you're trying to build. :)
