### ISSUE TITLE
@debugforwardlist duplicate debug messages

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1059]
If you are the owner of an object which is also set DEBUG, and you are also on the @debugforwardlist of the object, you receive double debug notifications.

I am sure this is something that rarely happens, but a bug nonetheless.

**Comment by talvo** [comment]
Technically it's working exactly as it says. You ask for it twice, and you get it twice.

... Yeah, yeah, OK, fine.

**Comment by mike347** [comment]
Yeah, I've only run into this when debugging an object I don't own, and
then chowning it for further debugging (e.g. Verbose + puppet).
Technically not a bug maybe, but not useful behavior. :P

While on the subject, possible to add attribute generating the debug into
to the debut output?
E.g. #123/FN_MIKEBUGS!
Maybe only if the object is set verbose.
