### ISSUE TITLE
Accented & Moniker'd name function

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1063]
You can have an accented name. accname()
You can have a monikered name. moniker()
Why can't I have a moniker'ed, accented name? :)

Please, Santa Mike. Make this a reality.

**Comment by talvo** [comment]
Anyone know if/how MUX or Rhost make this available? I'm not even sure where to find MUX now (the MUX website and Google Code page just link back to each other).

**Comment by talvo** [comment]
It seems that both MUX's moniker() and Rhost's cname() show accented names, so I guess we can just change ours to do likewise.
