### ISSUE TITLE
Hidden-reconnect on channels

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1065]
I believe the intended behavior is that if you are hidden on a channel, and the channel isn't Admin/Wizard only, you will not trigger the '* has connected/reconnected' messages on a channel.

A @hidden (and channel @hidden) Admin logged in, and on a non Admin/Wiz channel, it broadcast 'Soandso has HIDDEN-reconnected.'

Is this a bug or intended behavior?

**Comment by mike347** [comment]
Okay, this happens if you are reconnecting hidden, while your old (stale?) connection is /not/ hidden.
I'm not sure if it's a bug or working as intended, but to me it looks like a bug. If you are trying to connect hidden, it should be done quietly, no?

**Comment by talvo** [comment]
It looks like it's using Dark() checks to determine if the message should be shown or not, despite the fact that Dark players do show up, and Hidden ones don't. Time for some tweaking.

**Comment by talvo** [comment]
In fact, in this day and age, we should really do this properly, pass the descriptor to chat_announce(), and instead of only announcing hidden connects on admin-only channels, we should just check each person on the channel for hidden connects and see if they can hear it or not.

**Comment by mike347** [comment]
Sounds good. :)

**Comment by mike347** [comment]
Any progress on this, Mr Talvo? :)
