### ISSUE TITLE
sortby() Doesn't Preserve Relative Positioning

### ISSUE THREAD

**Issue by Dex-Sinister** [pennmush/pennmush#1067]
Input example:
think sortby(lit(#lambda/sub(last(%0,.),last(%1,.))),A.1 A.2 B.1 B.2 C.1 C.2)

Expected output:
A.1 B.1 C.1 A.2 B.2 C.2

Actual output: Randomised. Examples include:
B.1 C.1 A.1 A.2 C.2 B.2
B.1 C.1 A.1 C.2 A.2 B.2
C.1 A.1 B.1 C.2 A.2 B.2
A.1 B.1 C.1 B.2 A.2 C.2

When items are equal, I would expect that sortby() would preserve their original relative positions. This would allow nested sortby()s to sort hierarchically. This does not seem to be the case. Is there any way to force this in softcode?

**Comment by talvo** [comment]
Preserving their original position is generally an inefficient waste of time - you're telling the sorting algorithm they're identical, so their original position is irrelevant.

You can do it in softcode by using a method of sorting that makes them unique instead, such as

th setq(0,A.1 A.2 B.1 B.2 C.1 C.2)[sortkey(#lambda/last(%%0,.) \[member(%q0,%%0)],%q0)]
