### ISSUE TITLE
errors in `make portmsg`

### ISSUE THREAD

**Issue by mcgiwer** [pennmush/pennmush#1069]
**Output:**

$ make portmsg

(cd src; make portmsg "CC=gcc -std=gnu99" "CCFLAGS=-g -O3 -W -fstack-protector -Wa,--noexecstack -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char    " \
	"LDFLAGS=-Wl,-z,noexecstack   " "CLIBS=-lpcre -lz -levent_openssl -levent_extra -levent_core -lcrypt -lm  -lpcre -lssl -lcrypto   " )
make[1]: Entering directory `[trunchated for security reasons]/pennmush/src'
gcc -std=gnu99 -g -O3 -W -fstack-protector -Wa,--noexecstack -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char     -DSLAVE -o portmsg portmsg.c mysocket.c sig.o \
	wait.o -Wl,-z,noexecstack    -lpcre -lz -levent_openssl -levent_extra -levent_core -lcrypt -lm  -lpcre -lssl -lcrypto   
portmsg.c: In function ‘lostconn’:
portmsg.c:93:3: error: expected declaration specifiers before ‘NORETURN’
   NORETURN;
   ^
portmsg.c:95:5: warning: empty declaration
     enum { MAX_CONNECTIONS = 15 };
     ^
portmsg.c:96:5: error: parameter ‘connections’ is initialized
     sig_atomic_t connections = 0;
     ^
portmsg.c:100:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
portmsg.c:114:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
portmsg.c:120:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
portmsg.c:224:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
portmsg.c:92:1: error: old-style parameter declarations in prototyped function definition
 lostconn(int sig)
 ^
portmsg.c:226:1: error: expected ‘{’ at end of input
 }

**Comment by shawnw** [comment]
You're probably the first person to try compiling that in years. Fixed.
