### ISSUE TITLE
Allowed characters in player and password

### ISSUE THREAD

**Issue by mcgiwer** [pennmush/pennmush#1071]
My idea is to add that the administrator can supply in the config file (separate for each):

* minimal and maximal length for username and password
* the characters with can be used for player name and password
* and more

This solution would allow to better customize the game without need of ingerence in source code

**Comment by shawnw** [comment]
Passwords should not have a maximum length. A minimum isn't a bad idea, though.

**Comment by mcgiwer** [comment]
the problem is, that users cannot use the underscore, minus nor space in player names, with makes difficult to use desired names

**Comment by shawnw** [comment]
You can use underscores and dashes. Spaces, too, with the right config setting.

**Comment by mcgiwer** [comment]
I tryed it and I recieved the error: "Bad name"

**Comment by MrWigggles** [comment]
Not every game allows for name with spaces.

**Comment by mcgiwer** [comment]
but I mean that the server with is downloadable from here should be allow to do it as default, with possibility to enable or disable it thru the config file

**Comment by MrWigggles** [comment]
Why?

**Comment by mrsenile** [comment]
I've been 'Ashen-Shugar' on every Penn based game I connect to.  If the hyphen was not a default character, I would have been a sad guppy with my desired name.

I'm not sure why the characters you see are restricted, but it could be you (or the game that you're asking about) has a bad_name policy that contains the specific characters with possible wildcarding.

I'd look there first.

**Comment by mcgiwer** [comment]
@mrsenile some persones players have multi-part name and disallowing the hypern or underscore in this case is a bad idea

@MrWigggles please reas my post. We talk about the server with can be self downloaded, compiled and run ;)

**Comment by mrsenile** [comment]
For multi-part names you would need to surround it in double quotes.  So:  cr "This Is My Player Name" passwordgoeshere

**Comment by mcgiwer** [comment]
@mrsenile that's nowhere mentioned :p

**Comment by talvo** [comment]
Added a comment in mushcnf.dst about needing to quote names with spaces, and also in 'help matching'.
