### ISSUE TITLE
@mailquota command: Does not exist?

### ISSUE THREAD

**Issue by Kimojuno** [pennmush/pennmush#1077]
Hello,

I attempted to use the @mailquota command on PennMUSH 1.8.5p7 and 1.8.6p0, and on both the @mailquota does not work.

The help files reference the command on the following:

help mail
help @mailquota

The help file on the vanilla .zip has the commands listed in txt/hlp/pennmail.hlp

I made sure that I didn't, for some strange reason, restrict the command and found nothing in the restrict.cnf file, so I can only guess that either it was removed in a previous release -- and still referenced in the help files -- or the command is broken.

help @mailquota reference:

```
@mailquota <player>[=<limit>]

This attribute allows wizards to change the maximum number of messages a player can have in their inbox, override the mail_limit @config option for specific people. <limit> should be a number between 1 and 50000, inclusive.

  Example:
    > @alias *Walker=Complaints_Department
    > @mailquota *Complaints_Department=50000
    > @wall Please @mail any and all problems to Complaints_Department.

```
Thanks,
Kimojuno.

**Comment by talvo** [comment]
Hrm! Curious. It's actually a standard attribute, not a command. I just tested on a new 1.8.5p7 install (which created a fresh minimal db) and it's present for me there. It seems to be missing on `M*U*S*H` just like on yours, though. My guess is that it was missing at some point in the past and is thus not there in older dbs. I'll stick something in to re-add it.
