### ISSUE TITLE
Strange behavior while connecting to running server

### ISSUE THREAD

**Issue by mcgiwer** [pennmush/pennmush#1079]
Hello. I had downloaded and compiled the latest version avaliable from GitHub branch). After editing a few *.cfg files to configure the server to the need, I had started the server (I use Ubuntu 14.10). The strange behavior starts when I try to connect to the running server. I get the confirmation message that I got connected, but the welcome screen (with includes login) don't show up.

> telnet 127.0.0.1 4201
> Trying 127.0.0.1...
> Connected to 127.0.0.1.
> Escape character is '^]'.

In most of the logs are only "Start of log"

I had double checked and all patches link to valid files in the txt folder.

Could anyone help me to find what's wrong?

**Comment by talvo** [comment]
Difficult to say from the information provided. Is there anything at all in connect.log?

**Comment by HarryCordewener** [comment]
Can you log in? Is there an object that should produce a welcome screen?

**Comment by mcgiwer** [comment]
@HarryCordewener The screen with allow to login don't even show up after connecting to the server. The quoted is the only thing with showed up

@talvo in the connect.log is only following entry:

> START OF LOG.

**Comment by talvo** [comment]
Pastebin or attach your netmush.log? And also the result of doing

`netstat -an|grep LISTEN`

on the server?

**Comment by mcgiwer** [comment]
@talvo
`output trunchated for security reasons`

> tcp        0      0 0.0.0.0:4201            0.0.0.0:*               LISTEN      18907/netmud

**Comment by talvo** [comment]
netmush.log, too? Though it looks like it's listening on the port, so I'm not sure why Penn doesn't seem to be registering the connection...

**Comment by mcgiwer** [comment]
@talvo that I had contacted you guys to try finding a solutions for this strange issue. Do you tink that it may be some kind of bug in the server ?

**Comment by talvo** [comment]
You still haven't included your netmush.log, which may shed some light on the problem. What are your ip settings in mush.cnf? (I'm guessing blank?) Try changing it to 127.0.0.1 and see if that causes any change in output/error message in the log.

**Comment by mike347** [comment]
May I recommend you login to M*U*S*H at pennmush.org 4201 for live support? You can join the Hardcode channel and may be able to resolve this a little easier. Just  suggestion.

**Comment by mcgiwer** [comment]
@talvo attaching the netmush.log file and the ip_address is set to 127.0.0.1
[netmush.log.txt](https://github.com/pennmush/pennmush/files/250439/netmush.log.txt)


@mike347 I messaged there and still waiting for any reply

**Comment by talvo** [comment]
Resolved.
