### ISSUE TITLE
Installing Penn on Raspbian

### ISSUE THREAD

**Issue by chazlehmann** [pennmush/pennmush#1080]
I've spent a few hours today trying to install Penn on Raspbian. I got lots of compile errors and netmush was never created.

I then found that I could:

sudo apt-get install pennmush-common

but after doing this couldn't find anything but the .deb files.  I'm sure that I'm missing something obvious.  It's been about 15 years since I've played with Penn, and the rust is showing.

**Comment by talvo** [comment]
The version you'll find in apt will be extremely old. What build errors did you get trying to compile the latest version?

**Comment by chazlehmann** [comment]
Here's the output from the make attempt I just did:

pi@HAL9000:/usr/local/src/pennmush-185p7 $ sudo make
/usr/bin/perl utils/mkcmds.pl commands
Rebuilding command prototype header.
File hdrs/cmds.h updated.
/usr/bin/perl utils/mkcmds.pl functions
Rebuilding function prototype header.
File hdrs/funs.h updated.
Making all in src.
(cd src; /usr/bin/make all "CC=gcc -std=gnu99" "CCFLAGS=-ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char   " \
"LDFLAGS=" "CLIBS=-lpcre -lz -lcrypt -lm  -lpcre -lssl -lcrypto " "MAKE=/usr/bin/make" \
"MAKEFLAGS=" "SQL_CFLAGS=" \
"SQL_LDFLAGS=")
make[1]: Entering directory '/usr/local/src/pennmush-185p7/src'
rm -f ../hdrs/buildinf.h
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o access.o access.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o atr_tab.o atr_tab.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o attrib.o attrib.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o boolexp.o boolexp.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o bsd.o bsd.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o bufferq.o bufferq.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o chunk.o chunk.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o cmdlocal.o cmdlocal.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o cmds.o cmds.c
gcc -std=gnu99 -ggdb -g -O2 -W -Wall -pedantic -Wno-comment -Wno-char-subscripts -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char       -c -o command.o command.c
In file included from <command-line>:1:0:
command.c: In function ‘command_parse’:
./../options.h:81:26: error: expected expression before ‘=’ token
 #define CHAT_TOKEN_ALIAS = /* */
                          ^
command.c:1181:8: note: in expansion of macro ‘CHAT_TOKEN_ALIAS’
   case CHAT_TOKEN_ALIAS:
        ^
<builtin>: recipe for target 'command.o' failed
make[1]: *** [command.o] Error 1
make[1]: Leaving directory '/usr/local/src/pennmush-185p7/src'
Makefile:38: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by talvo** [comment]
The CHAT_TOKEN_ALIAS should be in single quotes; edit options.h and set it to
`
#define CHAT_TOKEN_ALIAS '='
`

**Comment by chazlehmann** [comment]
That worked beautifully.  Thank you!  Can you point me to something that might teach me how to do a script that will boot Penn when the machine starts up?  It seems like I saw something somewhere, but I can't find it for the life of me.  I've got penn chowned to a user account that does absolutely nothing else.

**Comment by talvo** [comment]
Not an area I know a great deal about, I'm afraid, and it tends to vary pretty widely between systems. The best place to look is probably on the wiki for the OS you're using.
