### ISSUE TITLE
Relative Nested Attributes

### ISSUE THREAD

**Issue by Crunch219** [pennmush/pennmush#1083]
Currently, whenever referencing nested attributes, you always have to give the full attribute name. Would it be possible to have them relative? For example, if you were in FOO`BAR`BAZ, and you wanted to refer to FOO`BAR`XYZ, you could do ufun(`XYZ).

**Comment by talvo** [comment]
I think this actually sounds kinda cool and useful. Anyone else?

**Comment by MrWigggles** [comment]
I think it might be better if it was more like lattr, and you can just insert wildcards in the trees. 

u(*`xyz)

Having it follow similar/same rules as the lattr and related functions would be best in my opinion.

**Comment by Crunch219** [comment]
Hmm, I certainly get your point about consistency, but how would the wildcards behave? Unlike lattr() where we can target multiple branches, u() can only ever target one specific attribute at a time, can't it? So if it used wildcards and the wildcard could match multiple attributes, would it give an error code, or what would happen? Wouldn't an error like that lessen its usefulness? One of the main reasons I'd really love this is (aside from saving text space) it allows things to be moved around in the same object or ripped/added to other objects really easily with something like @cpattr/@mvattr. And I'd think this would be implemented everywhere consistently, not just in u(). lattr() and any other function would be able to have the same thing, wouldn't they? So in fact, you could do lattr(`XYZ`*) to be equivalent to lattr(FOO`BAR`XYZ`*).

**Comment by talvo** [comment]
Yeah, unrelated syntax to wildcards, and as Crunch says, it would be a global syntax that could be used anywhere. You could do, for instance:
```
&foo me=$+set *=*: &`%0 me=%1
+set bar=baz
```
which would set
```
FOO`BAR
```

**Comment by HarryCordewener** [comment]
Meh. 
%= usually serves this function if you're coding it well.

**Comment by talvo** [comment]
This is true;
```
ldelete(%=, -1, `)
```
serves pretty much the same purpose. I still think the syntax is kinda cool, but possibly not worth the effort when it can be quite easily obtained already in softcode.

**Comment by talvo** [comment]
I still think this is cool, but the consensus seems to be that it's not worth adding. Boo. ;)
