### ISSUE TITLE
NAMEFORMAT bug with flags() within ufun

### ISSUE THREAD

**Issue by Crunch219** [pennmush/pennmush#1088]
I tried calling `u(#dbref/NAMEFORMAT)` from a different room's description, and all hell broke loose. The @nameformat was set up as:

    [ansi(h, Room)][if(controls(%#, me), (%0[flags(%0)]))]

This caused the following when looked at from the desc of the other room:

    Room(AAaCxCDbdeFFghHJklL^mMm~qnN"NwoOipQrXZSxtIUvVWZ)

The same issue happens when THINK is used, and probably any other method of calling it except by looking I guess. It works just fine with the normal look command while in the room.

    Room(#12345RwnFJ)

**Comment by talvo** [comment]
Not a bug - you aren't passing a value for %0. Which means flags() is being called with no argument. When that happens, it returns a list of all flag characters.
