### ISSUE TITLE
Change rjust()'s truncate behaviour to match Rhost/MUX

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1092]
On MUX, `rjust(foobar,3)` returns `foo`. On Rhost, `rjc(foobar,3)` returns `foo`. On Penn, `rjust(foobar,3,,1)` returns `bar`. Changing this would not be backwards-compatible but, given that it's a relatively new behaviour, desirable; the fact that we do it differently to everyone else is enough to class it as a bug, IMHO.

Any strong objections?

**Comment by MrWigggles** [comment]
Hrm. 
Sure.

**Comment by mrsenile** [comment]
You could consider to allow the 'bar' behavior if you give it '-1' instead of '1'.  I can see some use for the previous behavior.

**Comment by talvo** [comment]
I'd rather keep it boolean and just match the behaviour to everyone else, personally; if people want the other behaviour it's still only one more function call away.
