### ISSUE TITLE
Penn on Win10Bash

### ISSUE THREAD

**Issue by ray73864** [pennmush/pennmush#1097]
Possibility of changing how the configure script works things out so that people compiling on "Bash on Ubuntu on Windows 10" don't have to provide the "--disable-info_slave" and "--disable-ssl_slave" switches when running configure.

/proc/version has the following in it: Linux version 3.4.0-Microsoft (Microsoft@Microsoft.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Dec 31 14:42:53 PST 2014

**Comment by talvo** [comment]
Should also be done when $build_is matches cygwin, mingw or msys, too. (Took a quick look but it doesn't seem autoconf has any currently defined way of detecting Bash on Win10). @shawnw

**Comment by shawnw** [comment]
The unimplemented syscall that was responsible for this is now implemented, so those options aren't needed any more.
