### ISSUE TITLE
PennMUSH doesn't clean up MySQL correctly to deal with Single-result Stored Procedures

### ISSUE THREAD

**Issue by HarryCordewener** [pennmush/pennmush#1100]
MySQL will get out of sync with MySQL as it doesn't clean up properly after running a stored procedure.
The following articles are related.
http://t.pennmush.org/Me0TkV
http://t.pennmush.org/Me7Ild
http://t.pennmush.org/Me7Db8

**Steps to Reproduce:** 
1. Create a Stored Procedure.
2. Run the Stored Procedure twice from PennMUSH.
3. Note that the second run has an error claiming the commands are out of sync. (Requiring `@shutdown/reboot` to resolve.)

**Comment by HarryCordewener** [comment]
For the Stored Procedure I used to test this, check out:
http://mush-mercutio.tumblr.com/post/153345784737/pennmush-graph-framework

**Comment by talvo** [comment]
I believe this is now fixed by the above pull request (and 1d92c3a5aaf585ef8bea46b34101cef92fc9ca08 for the changelog), but Merc can correct me if I'm wrong.
