### ISSUE TITLE
extract with one arg returns incorrect result

### ISSUE THREAD

**Issue by JulesLetters** [pennmush/pennmush#1102]
<Softcode> Jules says, "Am I reading this wrong, or do I have a bug?  Help extract() says that extract with one arg will work like first(), but I get extract(a b c) -> b"
<Softcode> Softcode Vampire qa'toq says, "which is interesting because 'extract(a b c)' => b, extract(a b c, 0) => <nothing>, extract(a b c, 1) => a"
<Softcode> Softcode Vampire qa'toq would say that extract with just the list is broken, bug report it on github :)

**Comment by HarryCordewener** [comment]
Yeah, that is incorrect. It should default to 0.

**Comment by HarryCordewener** [comment]
To be closed by commit: 954dc5da90dacac1aec8803885b0ddb185fa53fd

**Comment by talvo** [comment]
Beat you to it :)
