### ISSUE TITLE
OpenSSL 1.1 incompatibilities

### ISSUE THREAD

**Issue by Chalice** [pennmush/pennmush#1104]
Greetings Folks,

It seems like current Penn code has some incompatibilities with the revamped OpenSSL 1.1 library.

I fixed some of the issues in the attached diff file, but in the end OpenSSL 1.1 removed SHA0 support, so after applying my diff you are left with

`funcrypt.c: In function ‘fun_sha0’:
funcrypt.c:301:3: warning: implicit declaration of function ‘SHA’ [-Wimplicit-function-declaration]
   SHA((uint8_t *) args[0], arglens[0], hash);
   ^~~
mycrypt.c: In function ‘mush_crypt_sha0’:
mycrypt.c:47:3: warning: implicit declaration of function ‘SHA’ [-Wimplicit-function-declaration]
   SHA((uint8_t *) key, strlen(key), hash);
   ^~~

<snip>

funcrypt.o: In function `fun_sha0':
/home/ambmush/PennMUSH-GIT/src/funcrypt.c:301: undefined reference to `SHA'
mycrypt.o: In function `mush_crypt_sha0':
/home/ambmush/PennMUSH-GIT/src/mycrypt.c:47: undefined reference to `SHA'
collect2: error: ld returned 1 exit status`

[Penn186_OpenSSL-1.1.0.diff.zip](https://github.com/pennmush/pennmush/files/625052/Penn186_OpenSSL-1.1.0.diff.zip)

Hope this helps somewhat!

--Ambrosia@M*U*S*H

**Comment by shawnw** [comment]
Changed the configure script a while back to check for SHA.
