### ISSUE TITLE
Guest Login Issue

### ISSUE THREAD

**Issue by g33kcub** [pennmush/pennmush#1106]
When I have multiple guests. Guest, Guest1 Guest2 etc..
If the name for Guest (The first one) is changed through a +myname system or something similar. Additional guests can only log in if you use co guest1 etc. 
This shouldn't happen. The system should recognize each guest and allow it to roll to any dbref that is guest empowered. 
Rhost had a config that let us define the DBREFS for our guest characters, this prevented the confusion with the rename, I think this is a good solution and should be rolled into penn to support non-guest names.

**Comment by talvo** [comment]
Just set the `@alias` for one of them to Guest, if you want people to be able to use 'connect guest' at the login screen.
