### ISSUE TITLE
@pemit doesn't respect interact locks

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1107]
`@pemit` (and other commands that use `do_pemit`, like `@message` and `@prompt`) don't respect `@lock/interact` when checking who to send messages to. `@emit` and `@oemit` do. They probably all should.

**Comment by talvo** [comment]
Apparantly this one is my bad, and it's documented that `@lock/interact` only blocks indirect sound, and not stuff directed to specific people. Still not sure whether or not I'd change it, though; thoughts?

**Comment by shawnw** [comment]
I don't think anybody had any thoughts.
