### ISSUE TITLE
Config option to have %t return spaces

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1113]
Since tabs are the devil for layouts, add a config option tab_spaces that, when set to a number > 0, makes %t return that many spaces, instead of a tab character.

**Comment by talvo** [comment]
Hrm. Should the change to spaces be instant (%t literally returns a bunch of spaces), or should %t still return a tab character, but it should be translated to spaces on output?

I'd be inclined to go with the former, since it will then make softcode operations easier, but it would break code that uses %t as a delimiter.

**Comment by shawnw** [comment]
I vote for leaving it unchanged and encouraging people to use other things to align text.

**Comment by tkrajcar** [comment]
Agreed with @shawnw, I don't think `%t` is commonly used enough in 'new' code to warrant any time spent offering more options for how it works, and we certainly don't want to break old stuff.
