### ISSUE TITLE
table() includes output separator in line length

### ISSUE THREAD

**Issue by Degraine** [pennmush/pennmush#1119]
When calculating how many fields can fit into a single line, the ~~delimiter~~output separator is included, so if I create a table with a field length of 20 and a line length of 62, the table will only have two columns.

EDIT: Corrected terminology.

**Comment by HarryCordewener** [comment]
This is because of the output seperator, not because of the delimiter. The output seperator is a space.
See: table(a b c d,20,62,%b,) if you want to not have 2 columns.

Not a defect.

**Comment by shawnw** [comment]
commit c235a2e fixes this. Not sure if it'll stay though - I'm worried about this breaking code that takes the issue into account.

**Comment by shawnw** [comment]
Nobody's complained yet; closing.
