### ISSUE TITLE
Error during make install on MacOS Sierra

### ISSUE THREAD

**Issue by chromancer** [pennmush/pennmush#1123]
Partway through installation, I get the following error which I can't really make heads or tails of.

```
gcc -g -g -O2 -W -fstack-protector -Wa,--noexecstack -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char   -I/usr/local/include -I/usr/include   -c -o mycrypt.o mycrypt.c
In file included from mycrypt.c:21:
../hdrs/externs.h:103:23: warning: '/*' within block comment [-Wcomment]
/* #define COMP_STATS /* */
                      ^

mycrypt.c:41:29: warning: unused parameter 'key' [-Wunused-parameter]
mush_crypt_sha0(const char *key)
                            ^

mycrypt.c:86:14: error: variable has incomplete type 'EVP_MD_CTX' (aka
      'struct evp_md_ctx_st')
  EVP_MD_CTX ctx;
             ^

/usr/local/include/openssl/ossl_typ.h:92:16: note: forward declaration of
      'struct evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^

mycrypt.c:112:14: error: variable has incomplete type 'EVP_MD_CTX' (aka
      'struct evp_md_ctx_st')
  EVP_MD_CTX ctx;
             ^

/usr/local/include/openssl/ossl_typ.h:92:16: note: forward declaration of
      'struct evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^

2 warnings and 2 errors generated.
make[1]: *** [mycrypt.o] Error 1
make: *** [all] Error 2
```

At this point the installation halts. I think it may have something to do with OpenSSL, but I just installed 1.1, which seemed to go swimmingly. Is there some incompatibility here?

**Comment by talvo** [comment]
When you say you just installed it, did you download OpenSSL from source and build it yourself, or install it through the MacOS package stuff? I recall someone saying that Apple very helpfully screwed around with the copies they provide and removed some important stuff, so you may need to built it yourself from source if you didn't.

**Comment by shawnw** [comment]
Is this still an issue? I made some changes to the relevant code recently after it started breaking in the same way on other  OSes.

**Comment by shawnw** [comment]
Closing; assumed to have been fixed.
