### ISSUE TITLE
Add @lock/chown

### ISSUE THREAD

**Issue by CLDawes** [pennmush/pennmush#1127]
At the moment, I spend most of the time between setting something `CHOWN_OK` and it actually being `@chown`'d worrying about the possibility of someone, somehow, jumping in and stealing that item from its intended owner.
While this is somewhat protected against by the 'holding' requirement for `THINGS`, this protection does not seem to extend to `ROOMS` (at least as far as the `@chown` helpfile seems to suggest). A universal way to restrict the `@chown`ing of any `OBJECT` would fix this issue, and my best suggestion for this is `@lock/chown`.

**Comment by talvo** [comment]
Done in 9f3063deb028c19d5ed0bb9276abf0d6d3bc3974.
