### ISSUE TITLE
@nuke to take list of dbref#s to nuke

### ISSUE THREAD

**Issue by ray73864** [pennmush/pennmush#1129]
@nuke should allow a space-seperated or comma-delimited list of dbref#s to @nuke!

Why? Because Kitai said so, and if Kitai is not happy then the world is an unhappy place!

Command: @nuke <list of dbref#s>
eg: ```@nuke #3 #4 #100 #120```

:D

**Comment by talvo** [comment]
`@dolist` is your friend.
