### ISSUE TITLE
OSX / Mac Hint

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1135]
Helping 'lolkje' fix an issue he had compiling Penn on OSX, he kept running into a situation where configure found pcre, but could not find pcre.h and would fail.

This seems to be related to upgrading from an earlier version of OSX.. to fix it, xcode tools need to be updated.

'sudo xcode-select --install'
then run ./configure again.

Thought it might be prudent to add this to the mac hints file.
-Qon

**Comment by shawnw** [comment]
Added in b5932b8a
