### ISSUE TITLE
send() error 

### ISSUE THREAD

**Issue by MUSHPark** [pennmush/pennmush#1136]
OS: FreeBSD 9.3
Penn version: 1.8.6p1

Upon producing large-ish amounts of output, user is disconnected and a message similar to this is logged in trace.log:

[09/05 14:48:42] send() returned -1 (error Resource temporarily unavailable) trying to write 74 bytes to 15

This happens reliably and repeatably, with any command that produces a large amount of output: examine of an object with large amounts of data, @search all (10706 objects in DB), @setting objects DEBUG and executing code on them, etc.

This occurs regardless of whether the player is privileged or not.

Problem does not occur on Debian Linux

[config.log.txt](https://github.com/pennmush/pennmush/files/1278626/config.log.txt)
[mush.cnf.txt](https://github.com/pennmush/pennmush/files/1278627/mush.cnf.txt)

**Comment by shawnw** [comment]
I see the problem. Will commit a fix tonight.

**Comment by shawnw** [comment]
87d39867 should fix it. Will leave open for a while in case it doesn't.

**Comment by MUSHPark** [comment]
This seems to have fixed the problem. After the change, no issues with large output.

Thanks a bunch for the quick response!

--Oleo

**Comment by shawnw** [comment]
Closing then.
