### ISSUE TITLE
Request: Guests and Channels

### ISSUE THREAD

**Issue by Kimojuno** [pennmush/pennmush#1137]
I seem to recall guests used to be able to join channels, but can no longer do so.

Would it be possible to allow guests to only join set channels? For example, a channel marked with a guest option? This way you still limit what channels they can join but they can still ask questions.

Thanks!

**Comment by mike347** [comment]
Not sure if this is the solution you're looking for, but wizards can force guests onto channels.
e.g. '@chan/on Recruiting=Guest'

**Comment by Kimojuno** [comment]
That does help, but isn't really permanent solution I think. I'm guessing @force guest=@chan/on guest ?

I just tried that and it didn't work. No acknowledgement either.

**Comment by mike347** [comment]
It's permenant. We did it once, twenty years ago, and the guests are still on the channels. :)

@forcing the guest won't work, because the still don't have permission to join the channel. A wizard has to @chan/on <channel>=<player> them.

**Comment by mike347** [comment]
Sorry, I didn't realize it was eating the code.
`@chan/on <channel>=Guest`
e.g.
`@chan/on Recruiting=Guest`

**Comment by Kimojuno** [comment]
Thank you! That worked. Appreciate it, Mike. Thank you!
