### ISSUE TITLE
@linking to a player

### ISSUE THREAD

**Issue by Eckspert** [pennmush/pennmush#1141]
After much digging and trying to rip apart space and time, I found that even though there are checks put in place to prevent a recursive issue in rooms by players location being set inside themselves, it is still possible to @link an exit to a player. 

Further reading, it appears in move.c,  in the do_move function body, there is still a blank case called TYPE_PLAYER under the switch for  Typeof(var_dest), that shows that players, were at one time or maybe will be allowed to again in the future,  be set as a possible destination.

The fact you are allowed to set a player as a destination, but are unable to pass through the exit with out getting an invalid destination error seems a bit redundant. 

The result of my hacking did in fact show me, you cannot exist inside yourself, sadly. Instead, I ended up hanging the mush process. What a better hiding place than inside ones self.

**Comment by Eckspert** [comment]
It was brought to my attention why there is a case TYPE_PLAYER. It was explained that with out a break in TYPE_PLAYER, it trickles down and acts like TYPE_THING.

**Comment by tkrajcar** [comment]
Am I correct in thinking this can be closed? It doesn't appear to be possible to `@link` an exit to a player, unless I'm missing something.

I do sort of miss the (old, not sure if it's still true) TinyMUX behavior where you could be inside yourself AND players were also valid origins for exits... so you could `@tel` inside yourself and then open a bunch of "personal shortcut" exits to various rooms 😄

**Comment by talvo** [comment]
> It doesn't appear to be possible to `@link` an exit to a player, unless I'm missing something.

It is possible to link an exit to a player (but only if you specify them by dbref - other forms of matching, like `*playerName`, don't work). 

> The fact you are allowed to set a player as a destination, but are unable to pass through the exit with out getting an invalid destination error seems a bit redundant.

This is not the case. You can link an exit to a player and then go through it. Your issue is that you're trying to link an exit to *yourself* and then walk through it, and (whether walking through an exit, teleporting or using 'enter') it's never possible for an object to be inside itself.
