### ISSUE TITLE
Turn a mush into a web server

### ISSUE THREAD

**Issue by shawnw** [pennmush/pennmush#1144]
Penn already detects HTTP requests and returns an error. It probably wouldn't be hard to add a way to run softcode on requests instead and send its output back...

http://mush.pennmush.org:4201/WHO etc.?

**Comment by talvo** [comment]
See #1032, #1093

**Comment by shawnw** [comment]
Those could be implemented in terms of what I'm envisioning, by returning JSON instead of HTML, sure.

Basically: Have an http handler object, much like we have an event handler object now, with GET paths mapped to attributes (GET /foo/bar -> &foo`bar), and evaluating that attribute with various useful bits passed as arguments or in registers to get the body of the reply (Which does limit it to 8k...). Use q-regs to specify stuff for the header, like response code if it's not 200, content-type, etc. Each request gets queued up and run much like it was a 'think u(#1234/foo`bar, ...)` done by a connected player

**Comment by shawnw** [comment]
Current thinking on these issues:

Use an embedded http server library (Probably [CivetWeb](https://github.com/civetweb/civetweb)), running on its own port(s) in a separate thread instead of trying to make the main game port do it all.

Have a new queue for evaluating softcode handlers for web requests. Connection thread enqueues requests, and after they're evaluated in the main game thread, the results get sent back to it. This queue would be lower priority than the current in-game command queue.

Have a standard set of predefined request handlers that don't involve calling softcode at all, for cross-mush compatibility (WHO, INFO, etc. equivalents). Lets people write tools that work with any game, not just a specific one.

Also be able to serve static files, for css/javascript/etc. HTML template files with embedded softcode (And you thought PHP was bad)?

Figure out how to handle user authentication, cookies (Also need these in `@http`), etc...

**Comment by captdeaf** [comment]
This is done, w/ `@respond` and `@config http_handler`. :D.
