### ISSUE TITLE
Websock Client

### ISSUE THREAD

**Issue by grapenut** [pennmush/pennmush#1145]
I made a github repository and cleaned up the example websock client even further. Please change the link in CHANGES187.md to point here instead as it's a more reliable source.

https://github.com/grapenut/websockclient

Thanks
-grapenut

**Comment by grapenut** [comment]
I overhauled the wsclient.js library API, provided a more minimalist client index.html, and updated the README. Just clone the repo, drop it in a web directory, and it's ready to go. Change serverAddress and serverPort in index.html if the address is different from the web server or if the port is not 4201. You can easily use it as a barebones to build a more polished client, including graphical displays, popups with various data displayed, or seperate chat and main output windows.

https://github.com/grapenut/websockclient

**Comment by shawnw** [comment]
Done.
