### ISSUE TITLE
websocket: terminfo() support

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1146]
terminfo() should indicate when a client is a websocket client
e.g. inside FUNCTION(fun_terminfo), in bsd.c around line 6831, under if (hasprivs() {

Add:

```
if(is_ws_desc(match))
  safe_str(" websocket", buff, bp);

```

**Comment by grapenut** [comment]
While we're at it, websockets should probably show up in the SOCKSET command (but you shouldn't be able to toggle it obviously). Terminal negotiation needs to be cleaned up a bit as well so that websockets can automatically negotiate xterm256 and no prompt_newlines.

**Comment by shawnw** [comment]
Done, for terminfo(). Not adding it to SOCKSET, since it's not an option.
