### ISSUE TITLE
string_prefix() returns 1 on empty string

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1151]
If you give string_prefix() an empty string to match, it returns 1.
E.g.

```
string_prefix("foobar", "")
> 1

```
This is causing an invalid character login issue if you send a blank input to the login screen (as reported by Mike/Talvo).

Also, FWIW, several calls in the code call the function with the arguments reversed. According to the definition, it should be called as string_prefix(prefix,string). Several calls (e.g. in look.c, funmisc.c) give the string first and the prefix last. Might be something to look into.

**Comment by grapenut** [comment]
In case we don't want to change string_prefix(), i solved the invalid logins on blank input by adding a line in check_connect() of bsd.c, just after parse_connect(). Check if strlen(command) > 0, return 1 if not.

**Comment by shawnw** [comment]
An empty string *is* a prefix of any other string, though. So it's not technically wrong. Just maybe not desirable everywhere we use it.

**Comment by shawnw** [comment]
A lot of those funny string_prefix uses you mentioned really should be strcasecmp() calls as they're clearly intended to do exact matching, not prefix checking. Weird.
