### ISSUE TITLE
SSL client certificates

### ISSUE THREAD

**Issue by grapenut** [pennmush/pennmush#1155]
Websocket SSL connections fail when the config options `ssl_ca_file` or `ssl_ca_dir` are not commented out, regardless of `ssl_require_client_cert`. There is a typo in myssl.c:ssl_init() that causes the server to request a client certificate even if `ssl_require_client_cert` is turned off, but will only abort connections with invalid certificates if `ssl_require_client_cert` is turned on. However the client may abort if a client certificate is requested and it has none to send. I don't think there is a reason for the server to request a client certificate if it isn't going to check them.

You can bypass the typo in ssl_init() by commenting out both `ssl_ca_file` and `ssl_ca_dir`. The permanent solution would be to modify ssl_init() and change SSL_VERIFY_PEER to SSL_VERIFY_NONE if the `ssl_require_client_cert` option is off. I think this was probably the intended behavior and just a typo. Whenever `ssl_require_client_cert` is turned on it correctly uses SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT which will request a certificate and then fail if it's invalid.

Cheers,
-grapenut

**Comment by shawnw** [comment]
And merged.
