### ISSUE TITLE
lcon(<loc>,<type>) broken

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1160]
th lcon(here,thing) returns a list of players (but not things) in a room.
I have not done extensive testing to see what other issues arise, but lthings() is unaffected for what its worth.

**Comment by toktoktheeo** [comment]
lcon(here,thing) seems to work fine on my build of the server.
PennMUSH version 1.8.6 patchlevel 1 [12/XX/2016]
Git revision: 47cf470

**Comment by mike347** [comment]
That is a very old build.

**Comment by toktoktheeo** [comment]
At least we know now that this bug didn't exist at that time."^^

**Comment by talvo** [comment]
Bug caused by the recent switch from string_prefix() to strcasecmp(); fundb.c line 766 is
```
 if (strcasecmp("player", args[1])) {
```
but should be 
```
 if (!strcasecmp("player", args[1])) {
```
though I think @shawnw is planning to roll back on these and put the string_prefix() calls back anyway.
