### ISSUE TITLE
Higher limit for max_pennies and other configuration options

### ISSUE THREAD

**Issue by mtirado1** [pennmush/pennmush#1163]
The `max_pennies` config option has a limit of 100,000 that can't be increased in mush.cnf

The limit should be incremented to the max value that can be stored in an integer.

**Comment by talvo** [comment]
The primary use of pennies is for preventing runaway code, and the maximum unsigned int for 64 bit machines is way, way too high for this. If we ever implement an alternative for this and leave the pennies system purely as a cash system, then it's probably worth removing the option altogether and going with max_int. But until then, I would say definitely not.

Were there any other options specifically you wanted to the see the limits increased on? Doing it as a blanket change on all int options is definitely not a good idea.

**Comment by mtirado1** [comment]
The reason for the increment was to use the MUSH money as a cash system, but yeah, if it's used to prevent runaway code, then it's best to keep it that way.
