### ISSUE TITLE
Rewriting attribute handling

### ISSUE THREAD

**Issue by shawnw** [pennmush/pennmush#1164]
Currently, attributes are stored as sorted single-linked lists, one per object. The attr-arrays branch I just pushed changes this to use sorted arrays instead.

## Some advantages:

* Space savings. Between removing the need for a next pointer and rearranging struct members to eliminate alignment padding, the size of an attribute structure dropped from 40 to 24 bytes on 64-bit platforms. Some rough testing with a copy of M\*U\*S\*H's db showed a savings of 12+ mb of memory.
* Faster iteration of attributes thanks to better cache locality. The slab allocator used for attributes and other node-like structures *tries* to put nodes close to each other on the same page in memory, but using arrays ensures this, and goes beyond page to cache line adjacency.
* Faster lookups of specific attributes: Objects with a large amount of attributes switch from linear search to binary search. (Some benchmarking indicated the sweet spot was 32 attributes.)

## Current status:

Compiles and runs cleanly. Passes the test suite, though only the attribute tree tests really do much with attributes. Load's MUSHs db without obvious issues. Needs more testing, especially in attribute deletion, and in interactions with the $-command matcher and parents and attribute trees (Had to rewrite a big chunk of that code, and while it's a lot cleaner and easier to understand now, there might be some subtle difference that the attr tree testing didn't uncover).

So, not going to merge it quite yet, until I pound on it more, but the current code's available if anybody else wants to look at it and play with it.

**Comment by shawnw** [comment]
And merged into master after running on M\*U\*S\*H for a week or so.

**Comment by talvo** [comment]
Attribute trees are no longer sorting correctly after this patch (in lattr(), examine, etc). With the new code:

```
A A1 A`B A`BAR A`B`C A`B`C`D A`B`C`D`E A`B`C`FOO_BAR ACK ACK`TEST ACONNECT AFK A`FOO ALIAS ATT ATT`BASE3
```

Previously:
```
A A`B A`B`C A`B`C`D A`B`C`D`E A`B`C`FOO_BAR A`BAR A`FOO A1 ACK ACK`TEST ACONNECT ADD_NUMS AFK AFTER AGE ALIAS ARR ATT ATT`BASE3
```

Before, an attribute was immediately followed by its leaves, which is as it should be. Now they're in overall alphabetical order, ignoring the backticks.

**Comment by mike347** [comment]
This can probably be closed now? I believe https://github.com/pennmush/pennmush/commit/0466680cb8a1c0bdca7af3276ed4e44f9dbc0efc fixed this.
