### ISSUE TITLE
ENTER_OK Allows possessive take past @lock.

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1166]
.. why?
As per helpfile for 'get', you must pass the basic `@lock` and `@lock/take` of someone/something to take stuff from their inventory. But if they are set ENTER_OK, the `@lock/basic` is bypassed. This is not mentioned in the helpfile that I can find, and seems wrong.

**Comment by mike347** [comment]
So 'help locktypes2' describes @lock/take as relating to taking things from the objects's contents, but 'help @lock/take' describes it as relating to who can pickup the object itself. 

Perhaps this inconsistency is where the ENTER_OK overrides @lock/basic check in do_get() came from. Decide which behavior is the intended one, and adjust the helpfiles and code accordingly.

**Comment by talvo** [comment]
I agree that '`help @lock/take`' is incorrect, but otherwise I cannot. I have:
Wiz, set enter_ok.
Wiz is carrying Foo, no `@lock/basic`.
Mortal can `get wiz's foo`.

`@lock/basic Foo=!=Mortal`
`get wiz's foo` now fails for Mortal.

**Comment by mike347** [comment]
Not sure if it matters, but this is from an object.
Object is @lock/basic to it's owner, it has no other locks.
Object is set ENTER_OK
Mortal can get object's foo. Remove ENTER_OK, and it can't. Look at the code for do_get().

**Comment by talvo** [comment]
Not actually a bug, misunderstanding of which things on what affect what. But see also #1167.
