### ISSUE TITLE
isint() is limited to 32-bit integers on 64-bit systems

### ISSUE THREAD

**Issue by Pommpie** [pennmush/pennmush#1171]
Currently, if you shove a greater-than-32-bit integer into isint(), you get a 0 even if the system can handle 64-bit integers just fine. You can reproduce this on M\*U\*S\*H any time you're in the mood.

```
> th isint(2147483647)
1
> th isint(2147483648)
0
```

**Comment by shawnw** [comment]
That's deliberate. All the integer math functions use 32-bit ints.

**Comment by talvo** [comment]
Is it actually necessary, on 64 bit systems, though?

**Comment by shawnw** [comment]
Even any 32-bit system that Penn runs on supports 64-bit integers. Anybody want us to switch to them for softcode integers?

**Comment by shawnw** [comment]
And done. isint(), div(), bitwise functions work with 64-bit integers.
