### ISSUE TITLE
Unescaped comma warning shouldn't happen in escape()

### ISSUE THREAD

**Issue by MordantWastrel** [pennmush/pennmush#1172]
(or decompose(), probably)

This issue arises when escaping a comma-delimited list, e.g.

th [escape(foo,bar,baz)]

It seems like there are two ways of handling this:

1) Escape refuses the arguments because it's being overloaded and insists on a more correct syntax: ({foo,bar,baz})

2) Escape handles being overloaded gracefully and returns an escaped list.

2 is currently what happens, which is great. But it gives you this warning:

Unescaped comma in final arg of ESCAPE. This behavior is deprecated.

This warning is appropriate for any function that isn't escaping something, but given that the one and only purpose of escape() is to escape things, having unescaped content  is pretty much going to happen.

I think the easier request here is just to drop this warning when the function in question is escape() or decompose() since escape() already behaves very well. Otherwise you're taking a stand on syntax by insisting on the curly braces and breaking a lot of old code (eventually).

**Comment by annelions** [comment]
I'm pretty sure that escape() never took more than one argument in the first place nor does it take more than one now. And the same warnings happen for secure() and decompose(). Demanding {} around everything seems silly and arbitrary for these particular functions.

**Comment by MordantWastrel** [comment]
Yes, precisely. Escape(foo,bar,baz) is just overloading the function arguments -- and escape handles this just fine by treating it as a single argument of "stuff to escape."

It seems like the function parser is just picking this up as giving escape() multiple arguments that may contain unescaped commas (which is technically, literally true) even though contextually we can just assume that anything you feed escape(), secure(), or decompose() is always just a single argument of "things to escape"

**Comment by talvo** [comment]
Comma is the arg separator for functions. Quite a while back, someone decided to make some functions ignore commas in their last argument, to save people from having to escape them. Which is annoying, because it means we could never, ever add additional arguments to those functions in the future. So that behaviour was deprecated (and has been for literally years now), and will eventually be removed. Escape your commas, people.

**Comment by MordantWastrel** [comment]
Forgive me but your reply doesn't address this issue.

I am not asking that you accept unescaped commas as function arguments. It's already evident why that change was made.

This is a case where we have code iterating over a multi-dimensional list, which may contain individual elements like

foo,bar

And because we don't want those to be function arguments, we escape the element in the iteration with escape(). But it complains that we're passing unescaped commas ... **to escape()**

If what you mean is "escape every comma in your data because you can't actually use the escape function to escape commas in content," then that's what the help and warning should indicate. But the way it is now, it forces us to wrap every comma-delimited list in {}.

If that's what you want, that's fine too, but a) you should say that and b) it's cumbersome when the function you have already works quite well. Unless you're suggesting that there is some use case where you'd want to add an additional argument to escape() and decompose(), but I certainly can't think of any.

**Comment by talvo** [comment]
It's only an issue because you're *manually* passing your data to escape(), by actually typing `escape(foo,bar,baz)`. In any real-world situation, your data would be passed via `escape(%0)` or `escape(get(obj/attr))` in which case you wouldn't have a problem. (But also, in 99.99% of real-world situations, you don't actually need to escape - it's a virtually pointless function which is massively misused when not needed. Same goes for secure().)

**Comment by MordantWastrel** [comment]
The test case is meant to illustrate an actual problem. I hope it is obvious that I don't care about foo, bar, or baz.

I am looking at a database full of old code with attributes on db objects that contain multi-dimensional lists, and some of those lists are comma-delimited. Code iterates over those lists and calls escape(), either on the entire list or on the individual list item. If it calls it on the entire list, it seems like it's fine, but in some cases it escapes each list element separately (I know, why do this? ask 2003) but this reproduces exactly the test case. 

It's a perfectly legit call that you don't care about a use case like this since how hard is it to just pull the escape() out of the iter() and slap it on the get() which is way better anyway, but nevertheless it seems like you ought not be issuing a warning about unescaped characters when calling escape(). 

"but this only applies to pointless and misused cases" is fine as well, but this is MUSHCode we're talking about. eliminating barriers to maintaining old codebases would seem like a good thing.

**Comment by MordantWastrel** [comment]
Going through and rewriting all of it is preferable (when is it not?) but for the time being, the security measures (such as they are) consist of escaping ## where ## is being drawn from protected attributes sufficiently that the input may be presumed to be safe, or at least anyone with the power to make it un-safe doesn't need to hack ## to cause damage.

At any rate, "we won't change this because the code that produces this error is horrible" is a valid response. It's a barrier to Getting Things Done but if it's just our barrier then I would agree that resources are better spent elsehwere.

I stand by 'escpae() complains about unescaped input' as being counter-intuitive, even if what it really means is "get your act together and don't try to escape this, just call it differently"
