### ISSUE TITLE
@sql MySQL nested Stored Procedures causes Penn to Freeze.

### ISSUE THREAD

**Issue by volundmush** [pennmush/pennmush#1177]
See the title.

This happened when I ran a Stored Procedure on MySQL/MariaDB that used CALL to run a second Stored Procedure. The procedure executed perfectly but the softcode execution appeared to freeze. I'm not sure what specifically happened, but I feel as if perhaps the sql() call just never returned so the server keeps waiting on a thing that won't happen?

I had to use kill -15 to shut the game down... nothing I tried sending to it would do any good.

**Comment by shawnw** [comment]
Was this done with @sql, sql(), or one of the other commands or functions?

**Comment by shawnw** [comment]
Now that I've actually looked at the code...

I think there's an infinite loop in sql.c:penn_mysql_free_sql_query() when you do something that gets multiple result sets back, which it sounds like CALL does. I don't know enough about MySQL to say for sure, but it sure looks screwy. If I make a branch with some changes would you be willing to test it?

**Comment by volundmush** [comment]
Sure I would. That's easy to test! And it was used with sql()

**Comment by shawnw** [comment]
Just pushed a branch with a hopeful fix: issue-1177

**Comment by shawnw** [comment]
Should be fixed; re-open if it still happens.
