### ISSUE TITLE
align() with 'x' truncates whole words instead of by character

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1178]
`th align(<10x 10,Fleet Captain,Qon)`
`-->Fleet      Qon`
The expected output, IMO, is
`-->Fleet Capt`
So instead to defeat this, I need to use something like

`th align(<10x 10,mid(Fleet Captain,0,10), Qon)`
`-->Fleet Capt Qon`

**Comment by talvo** [comment]
Truncation (for both the x and X options) happens in exactly the same manner as wrapping - which means, if the string contains spaces, the last word is cut off (if not, it does truncate by character). 

Changing it would require checking for `if (lastspace && !(calign[i] & (AL_TRUNC_ALL | AL_TRUNC_EACH))` at line 1783, and moving the if() related to those into the else clause at 1804, by the looks of it.

**Comment by mike347** [comment]
I would say truncating by character is the better/moreuseful behavior.

**Comment by talvo** [comment]
I can never remember the right magic words to close a ticket from a commit on here.
