### ISSUE TITLE
orflags() fails if you check a flag not valid for that type

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1180]
If you try to check with orflags() a flag that is not valid for that type of object, instead of returning a 0, it returns #-1. I think this behavior is.. wrong.

Example:

`@flag/add NPC=+,thing,royalty,royalty`
`@create foobar`
`@set foobar=NPC`
`th orflags(foobar,rW+)`
`-->1`
`@set me=NPC`
`th orflags(me,rW+)`
`--> #-1 INVALID FLAG`

The correct way to handle this, IMO, is to treat the flag that is not available for that type of object as a negative result for that flag. Such that in the above example, it would return '1' because I am a Wizard, ignoring the invalid + flag.

**Comment by shawnw** [comment]
I agree. (And don't forget about andflags()/andlflags() too).
