### ISSUE TITLE
Re-Implement @toad so Mike can @toad me

### ISSUE THREAD

**Issue by mrsenile** [pennmush/pennmush#1185]
To keep Mike happy of course.

Though on a more serious note, there may be a nice feature for #1 to be able to convert data-types as an option.

**Comment by talvo** [comment]
Having given it some thought, and for the specific use-case given in the title, I can get behind this.

**Comment by shawnw** [comment]
@toad is too good for you. Also, the examples in Rhost's `wizhelp @turtle` are funny. But no.
