### ISSUE TITLE
Function version of @chown

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1186]
We have clone(), create(), etc. can we also have chown() ? I have a specific need for this, and could write it for my game, but I feel it could be used by others and should be part of penn.

Thanks
Qon

**Comment by ray73864** [comment]
Wrote this along time ago as I had a need for a functional version of @chown :)

```
FUNCTION(fun_chown)
{
  if (!command_check_byname(executor, "@chown") || fun->flags & FN_NOSIDEFX) {
    safe_str(T(e_perm), buff, bp);
    return;
  }
  do_chown(executor, args[0], args[1], args[2]);
}
```
Having it built into Penn would be better though. It was designed in a similar way to force(), trigger(), and wait().

**Comment by talvo** [comment]
Should this happen, I would be inclined to extend owner() rather than add chown().

**Comment by tkrajcar** [comment]
+1 to both this existing, and being an extension of owner().

**Comment by shawnw** [comment]
Not a fan of side effect functions, but since it appears that neither Rhost or MUX has a chown(), I'd go for an extension of owner() over a new function.

**Comment by mike347** [comment]
This was added with commit 4c762c3dd734ed43bee2ec9042f299878f0bacbb.
See `'help owner()'`
