### ISSUE TITLE
@chown/preserve on wizard-bit objects

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1187]
If you `@chown/preserve` a wizard-flagged object to another wizard, the wizard flag is still reset. Isn't this the whole point of the /preserve switch that the privilaged flags and powers are not reset?

The message it gives is:
`Warning: WIZ flag reset on #1234 because @CHOWN/PRESERVE is to a third party.`

Can we look into removing this?

**Comment by talvo** [comment]
Can't help thinking this defeats the point of /preserve, which is wizard-only and intended to.. well.. preserve priv flags and powers. I'm all for removing this and just warning that the object is [still] wizard.

**Comment by shawnw** [comment]
I agree; the current behavior seems wrong.
