### ISSUE TITLE
@malias owner and player destruction

### ISSUE THREAD

**Issue by shawnw** [pennmush/pennmush#1193]
When a player object is destroyed, any `@malias` they're a member of is updated, but ones they own aren't deleted or chowned, leading to things like 'scrabble' owning one.

Does anybody even use mail aliases, anyways?

**Comment by talvo** [comment]
There are certainly still plenty in existence; how often they're used, I don't know. 

Maliases should probably mirror the behaviour of player-owned channels (whatever that is) when the owner is nuked?

**Comment by shawnw** [comment]
Looks like channels get chowned to the player set as **probate_judge** . That's reasonable for maliases too, yes.
