### ISSUE TITLE
@mvattr to rename attributes causes crash

### ISSUE THREAD

**Issue by merittl** [pennmush/pennmush#1196]
I attempted to rename three attributes on an object using @mvattr to copy each attribute under the new names on the same object like so:

```
@mvattr #22/C.OOC=#22/C`OOC
@mvattr #22/C.OOC2=#22/C`OOC2
@mvattr #22/C.STAFF=#22/C`STAFF
```

The commands were all sent at once in MUSHclient, resulting in:

> Global Commands/C`OOC - Set.
> Attribute moved (1 copies)
> --- Disconnected on Sunday, June 03, 2018, 5:21 AM ---
> --- Connected for 0 days, 6 hours, 52 minutes, 51 seconds. ---

After restarting Penn and checking the object, no changes had been made to any of the attributes.  After trying a second time with the same result of having the game crash, I manually copied the attributes under their new names, then cleared out the old attributes.

> Version information:
> PennMUSH version 1.8.6 patchlevel 2 [12/19/2017]
> Git revision: 4c762c3
> Build date: Sun May 27 16:23:56 CDT 2018
> Compiler: gcc -std=gnu99
> Compilation flags: -g -g -O2 -W -fstack-protector -Wa,--noexecstack -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -funsigned-char   -I/usr/include -I/usr/include/mysql -DBIG_JOINS=1  -fno-strict-aliasing    -g -DNDEBUG

**Comment by mike347** [comment]
I've tried several different times on different servers to replicate this.. no luck. I don't suppose you have a core.* file and knowledge of gdb usage?

**Comment by talvo** [comment]
I've tried on one existing server and can't reproduce. I haven't yet tried on a totally new clone, however, which I think yours was, and it may be something specific to a new game/new db? Will try and test at some point soon.

**Comment by shawnw** [comment]
No crash (That was probably fixed already), but the first @mvattr to an attr tree that doesn't yet exist isn't deleting the original attribute and gives `Unable to remove 'C' because of a protected tree attribute.` I'll look into it tomorrow.
