### ISSUE TITLE
More JSON functions

### ISSUE THREAD

**Issue by shawnw** [pennmush/pennmush#1201]
Ways to insert or delete from keys and arrays... basically wrappers for some of the [sqlite3 json functions](https://www.sqlite.org/json1.html) like `json_insert()`.

The question is: individual functions, or a single aggregate function like `json_query()`? (If the latter, move patch from it to this new one to keep related functionality together). I'm kind of leaning towards the latter, calling it `json_modify()` or something.

**Comment by grapenut** [comment]
I'd prefer individual functions json_query() to retrieve data and json_modify() to change it. It's a little confusing to have one function that does everything. 

Maybe some shorthand aliases for JSON functions would be helpful too, like jget() and jset().

json_modify()/jset() could give us another way to build JSON strings. Chain them together to insert attributes with an empty object in the top level:
```
th jset(jset(\{\},prop1,val1,string),prop2,2.0,number)
```
would be equivalent to
```
th json(object,prop1,json(string,val1),prop2,json(number,2.0))
```

**Comment by talvo** [comment]
json_query already exists, grape.

I'd favour a single function for all the modifications; I don't think this is going to be widely enough used to be worth adding a bunch of individual ones or wrappers, certainly not right off the bat. If it ends up being extremely popular, we can look at adding them later.
