### ISSUE TITLE
BANG Support (From Rhost)

### ISSUE THREAD

**Issue by Eckspert** [pennmush/pennmush#1210]
BANGS NOTATION
  Bang notation allows you to use '!' and '!!' in functions for 'not' and
  'not-not' functionality.  This works similiarilly to the C equivelant of
  using 'bangs'.  A value of '1' means the condition was matched, '0' not.
  The following formats are available with BANG support ([] is return value):
    !   - 'not' BOOLEAN/MATH value.         Example:   !match(me,you)   [1]
    !!  - 'not not' BOOLEAN/MATH value.     Example:  !!match(me,you)   [0]
    !$  - 'not' STRING value.               Example:  !$grep(me,you)    [1]
    !!$ - 'not not' STRING value.           Example: !!$grep(me,you)    [0]
    !^  - 'not' TRUE BOOLEAN (like t())     Example:  !^grep(me,you)    [1]
    !!^ - 'not not' TRUE BOOLEAN (like t()) Example: !!^grep(me,you)    [0]
  
  You may also use these in %q<> substitutions,  %-<num> arguments, %i
  substitutions and %d substitutions.
  
  See 'help t()' for how TRUE BOOLEAN works.
    
  Example:
    > say match(one two three four five,four)
    You say "4"
    > say !match(one two three four five,four)
    You say "0"
    > say !!match(one two three four five,four)
    You say "1"
    > say !!$grab(this is a test,was)
    You say "0"
    > say !!$grab(this is a test,this)
    You say "1"
    > say !!^space(1000)                  (spaces are non-boolean strings)
    You say "0"
    > say !!$space(1000)                  (spaces are not-null strings)
    You say "1" 
    > say [setq(0,space(1000))]%q<!!$0> // %q<!!^0>     (process register 0)
    YOu say "1 // 0"     (spaces are not null // spaces are non-boolean)
    > say u(#lambda/[lit(%-!!$0 // %-!!^0)],space(10))  (process argument 0)
    YOu say "1 // 0"     (spaces are not null // spaces are non-boolean)
  
  Bang notation may or may not be enabled based on the RhostMUSH that you are
  on.  Please check @list options to see if it is currently enabled.
  
  See Also: %-, %q, %i, %d, t()

  Topic: SUBSTITUTIONS
 
  All messages may contain %-substitutions, which evaluate to gender-specific
  pronouns if the player's gender is set or to other useful information.
  Information returned is based on the player that caused the message to be
  displayed, not the object that stored the message or which is running the
  action list.  The substitutions available are:
 
    %s, %S  = Name, he, she, it, they.        (subjective)
    %o, %O  = Name, him, her, it, them.       (objective)
    %p, %P  = Name's, his, her, its, their.   (possessive)
    %a, %A  = Name's, his, hers, its, theirs. (absolute possessive)
    %n, %N  = the player's name.
    %k, %K  = the player's colorized/accented name.
    %w, %W  = the target dbref# of the twinklock (if applicable)
    %r      = carriage return.
    %t      = tab character.
    %b      = space character.
    %%      = literal '%' character.
    %0-%9   = Value of positional parameter/stack location 0 through 9.
    %-<num> = Stack 10+ that are comma delimited or if <num> specified
              the positional stack location 0 through 999.  BANGS supported.
    %-m     = The last command executed that issued @hook.  
    %i0-%i9 = Equivalent to itext(0) through itext(9). [%il for outer]
              BANGS supported.
    %d0-%d9 = Equivalent to dtext(0) through dtext(9).  [%dl for outer]
              Only useable with /inline only.  BANGS supported.
    %q0-%q9 = Value of registers.  Basically equivalent to [r(0)] - [r(9)].
              Note: You may use %q<label> or %q<0> as well.  BANGS supported.
    %qa-%qz = Extended value of registers.
    %va-%vz = Contents of attribute va through vz.
  
    NOTE: Anything that says BANGS supported may use BANGS for the process.
          example: %-!!$22 (see if arg 22 contains a string)
                   %q<!!$0> (see if register 0 is a string)
                   %q<!!$foo> (see if register with label 'foo' is a string)
                   %i!!$0 (see if iter()'s itext(0) is a string)
                   %d!!$0 (see if @dolist/inline's dtext(0) is a string)
  
{ 'help substitutions2' for more }

**Comment by talvo** [comment]
Adds very little functionality (which can all be achieved with one or two extra function calls or a slightly different approach) in a non-backwards-compatible way.
