### ISSUE TITLE
help/search fucked

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1225]
`help/search @force` now gives zero results, and `help search if you` gives fucking thousands, because it searches for either word, not the phrase I actually asked it to search for.

I'm looking at you, @shawnw.

**Comment by mike347** [comment]
help/find should be the default behavior for backwards-compat and alignment with other codebases (rhost), IMO.

**Comment by captdeaf** [comment]
I definitely agree. The new sqlite syntax should be `@search/query` or something similar, and `help/find` as default behavior.

**Comment by talvo** [comment]
ITYM help/search as the default behaviour. help/find is a new switch Raev added which currently has the original behaviour, while help/search (the original switch) has the new behaviour.

help/search should work as it always has (and as Rhost does).

I'm happy for the new behaviour to exist in some other fashion, whether it be as something like help/search/extended or help/find (though I do think having /find and /search is going to be confusing). But the original behaviour should be on the original switch

**Comment by captdeaf** [comment]
Yeah, oops, my bad. I vote `help/query` as the new behavior, `help/query foo OR this AND NEAR(whatever)`, help/search as traditional behavior.

`help/query` emphasises it has query-like behavior :D.

**Comment by talvo** [comment]
Done in 857073bf761fa5f3001e40e4c98638b8af62a137
