### ISSUE TITLE
HIGH IMPACT BUG: lattrp() and attribute trees

### ISSUE THREAD

**Issue by HarryCordewener** [pennmush/pennmush#1233]
## Bug Summary
**VERSION**: PennMUSH version 1.8.7 patchlevel 0 [08/10/2018] (rev 7dbec5a)
**Bug:** When using lattrp() from an inheriting object, it can't see its inherited attributes if it, itself, has a root attribute with a leaf.
 **Production-example**: https://pastebin.com/hfAhuwnH

**Comment by mike347** [comment]
Probably in atr_iter_get_parent() from a quick glance. Tagging @shawnw, as this is his magic.

**Comment by shawnw** [comment]
Hmm. I thought I'd replicated all the existing behavior with attribute trees and attribute visibility. I'll dig into it when I have a chance.

**Comment by shawnw** [comment]
Can I get a minimal complete example for this that demonstrates the problem? Decompiled objects that I can just paste into a 1.8.6 game and a 1.8.7 game to see how `lattrp()` differs between the two?

**Comment by HarryCordewener** [comment]
```
@create Child
@create Parent
@parent child=parent
&tree`leaf parent=5
&tree child=3
th lattrp(child/tree`)
```

**Comment by shawnw** [comment]
Okay. See if branch issue-1233 on https://github.com/shawnw/pennmush.git works better.

**Comment by HarryCordewener** [comment]
I'll try to get to this soon. The written unit tests look good though.

**Comment by HarryCordewener** [comment]
This change fixed the problem(s). That should be good to go.
