### ISSUE TITLE
Missing WS reboot info?

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1235]
@shawnw @grapenut 

> mushtype.h line 360
```
#ifndef WITHOUT_WEBSOCKETS
  /* TODO: Need to add this state to reboot.db. */
  uint64_t ws_frame_len;
#endif                /* undef WITHOUT_WEBSOCKETS */
```

Does this need doing, or does the comment need removing?

**Comment by grapenut** [comment]
That was already taken care of. You can remove the old comment.

**Comment by grapenut** [comment]
Also should probably go through and remove the WITHOUT_WEBSOCKETS blocks. I could submit a PR for that.

**Comment by shawnw** [comment]
Go for it.
