### ISSUE TITLE
Additional test harness

### ISSUE THREAD

**Issue by shawnw** [pennmush/pennmush#1238]
The current test suite uses softcode, and is quite nice. But I'm thinking it would be useful to have a test mode for things that can't be easily checked in softcode (Or checks in addition too). Whip up a basic test harness framework that lets you register test functions that then get called when netmud is started with a `--test` option sort of thing. Or use something off the shelf -- all the tools I know of are for languages other than C, but there's bound to be something.

**Comment by shawnw** [comment]
(A perfect trial for this would be the unicode stuff -- tests for all the low level utf-8 functions for example).

**Comment by captdeaf** [comment]
:+1: I approve of this idea.

Adding a `--test` with `TEST(test_name_whatever) {...}` everywhere sounds ideal. Just like we scan for `FUNCTION()` and collect, we can do the exact same for `TEST()`

And throwing in good checks around each TEST also makes sense, e.g: No remaining increase in the `mush_malloc()` check tree.

**Comment by shawnw** [comment]
Yeah, that's pretty much what I had in mind:

    TEST_FUN(a) {
       TEST("a.1", strlen("foo") == 3);
    }
    TEST_FUN(b) {
    }
    // TEST b NEEDS a

(The last bit to order tests (If `b` needs `a` to be working right so it can do its things, why bother to run it if `a` fails?))

With standardized error reporting if a test fails. What else would be useful to include?

**Comment by shawnw** [comment]
Got it up and running, with a basic framework and some sample tests to show how it works. (More to come before merging the PR, most likely).

This is something we should have done a long time ago.
