### ISSUE TITLE
Timezone enhancements

### ISSUE THREAD

**Issue by shawnw** [pennmush/pennmush#1255]
Currently, timezone offsets for softcode functions are read from an OS-provided database of timezone files. I'm pondering including the database with Penn instead -- useful for systems like Windows without it, or ones that put the database in strange places -- configure tries to find it, but...

One nice thing is security wise, it would stop us from reading files on disk based on arbitrary user-supplied strings. Current code does sanitize them, but safer to avoid that completely. This would also allow every game to have the same (hopefully current) rules and symbolic names, instead of depending on whatever package is provided by the server's OS.

Big issue is that du reports the database (It's stored as a directory tree of files in `/usr/share/zoneinfo` or wherever) is 5+ megabytes, so unless I can figure out a way to store the data more compactly, it'll be a dead end project. Maybe automatically download it on demand instead of including it if there's interest?

**Comment by HarryCordewener** [comment]
Might I suggest we look into tying straight into the SQLite time functions to deal with this - like we are dealing with JSON? This should also allow us to start using 64bit time for free.

**Comment by shawnw** [comment]
Good idea, but that would be in addition to this -- the time formats supported by sqlite include an optional timezone as an offset from UTC, but there's no support for finding that offset based on a symbolic name or location, daylight savings time, time zone changes over time as borders and rules get shuffled around, etc.

**Comment by HarryCordewener** [comment]
It's not hard to wget packages as part of an installation script. I believe Rhost does that. But this requires the location of this remote package to remain stable. I believe that github allows a directory of binary files you can just 'store as is' without it being part of the repo directly. 

I'm not sure that just the timezone file on its own is very worthwhile as a project, unless Windows is a big ticket issue for us (which would not have wget anyway, and you'd need to find a seperate way of doing that step just for windows). Most distributions are /decent/ about sticking it in a simple location. And I believe we allow people to pass in a location for the zoneinfo during configure anyhow, don't we?

**Comment by shawnw** [comment]
Closing as not worth the effort.
