### ISSUE TITLE
PCRE2 JIT compiling crashes on Cygwin

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#1257]
On Cygwin, at the very least, `pcre2_jit_compile()` leads to crashes (on startup, now that lots of wildcard patterns are converted to regexps carried out in `dbck()`).

@shawnw - not sure if this is likely to affect any other systems; I recall some had issues with jit in certain regexps previously. Any particular approach you want to take? I'm happy to just throw in a wrapper around the function so that it can be easily disabled at will for Cygwin users, if you don't want to do anything more in-depth atm.

**Comment by shawnw** [comment]
Interesting. I don't think it was with MSYS2 builds, but I'll check that again, see if it's something more generally Windows specific or not.

**Comment by shawnw** [comment]
More testing suggests it is Cygwin specific. I'll add disabling JIT on that platform into a PR I'm working on with a few other Windows fixes.
