### ISSUE TITLE
Socket Quota: Needs some attention!

### ISSUE THREAD

**Issue by volundmush** [pennmush/pennmush#1275]
The latest Penn updates 'fixed' the socket quota, limiting how quickly commands can come in and be processed.

This is a problem for those softcoders like me who have softcode systems consisting of 3,575 lines. I really can't deal with a code install of a single file taking a whole hour at 1-command-per-second.

There's a --disable-socket-quota launch flag, but this is not preserved at @shutdown/reboot.

I don't actually WANT these disabled for EVERYONE though if there's another option though. Perhaps some kind of @power or FLAG could come into play here that either grants a specific character a MUCH larger quota? Maybe mush.cnf options for how quickly the quota refills?

**Comment by mike347** [comment]
Okay so a few aspects here. I believe the original intent of the --disable-socket-quota flag was using it for testing purposes, and to not persist across reboots. But it's an easy fix if we want it to persist. 

Or break this out into two @config options: cmd_quota_burst, cmd_quota_rate, and maybe add a power NO_CMD_QUOTA, and allow GOD to bypass quotas automagically.

Though grapenut had a novel idea how to bypass this issue entirely, by uploading the code into a sql (lite?) DB, then using mapsql to quote it into the game. Pretty neat idea, but probably still a bit complicated for the intended audience of Volund's codesuite.

Looking for thoughts from other devs before I work on adding the config options.

**Comment by talvo** [comment]
Running arbitrary commands from SQL also invites evaluation issues if done without proper care, so I wouldn't recommend it as a general-use approach.

The option probably should persist across reboots (as we may, at some point, want the ability to use `@shutdown/reboot` in the test suite), but using this option permanantly and globally on running games is probably not desirable. A flag, power, or option of some kind is probably the better approach - possibly as something that gets set on a particular socket (not even player) by a wizard for a limited period of time, so it can be used briefly for mass-uploading code just as needed.

**Comment by mike347** [comment]
So maybe a @SOCKSET thing?

**Comment by talvo** [comment]
That sounds good. `@sockset <desc>=noquota, 45m` or something?

**Comment by mrsenile** [comment]
How we do it in Rhost:

@CMDQUOTA
  Command: @cmdquota <player> = <1-99999>
  
  This sets a tempoary maximum command quota for the target player's current
  connections.  This only works for connected players, and only sets it
  for the duration of the player being connected.  Once logged out of 
  their account, the value is reset to default maximum for either player
  or wizard, depending on their bitlevel.
  
  The value must be greater than 0 and less than 100,000.
   
  You may use @conncheck/quota to see command quotas of connected sockets. 
  
  Example:
    > @quota tinyplayer=10000
    @cmdquota: The target player tinyplayer for their online duration has
               command quota of 10000.
               Once this value is below 100 it will regenerate as normal.
  
  See Also: command_quota_max, wizcommand_quota_max, @conncheck


--------

Essentially it only effects the port/descriptor level for the command queue and once the player disconnects it resets their command queue to the normal defaults.  The command queue also does not regenerate as long as the custom value is greater than the max values.

We have a separate maximum (1000) to the normal player (100) command queue entry.

I figured 99,999 should more more than sufficient to load in even the largest softcode suites.

**Comment by mike347** [comment]
My thought as well, was to apply it to a socket and it expires when they logout or turn it off. I dont think it needs a timer to turn off automatically.
