### ISSUE TITLE
'help helpfile2'

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1282]
The helpfile 'helpfile2' can't be found using 'help helpfile2', you have to use 'help help2'.

`-->help helpfile2`
`No HELP entry for 'helpfile2'. Did you mean 'HELPFILE'?`

`-->help help2`
`help helpfile2
  Displays help entries that match <pattern>. If the /brief switch is given, only shows the names of matching entries. Without it, also shows a fragment of the entry with matches underlined.
....`

Seems to be an issue with the help command. You can see in the helpfile itself, that the help entry is named helpfile2.

**Comment by shawnw** [comment]
Its title in the help file is `help helpfile2` for some reason instead of just `helpfile2`. Easy fix.
