### ISSUE TITLE
wshtml() can't handle ansi

### ISSUE THREAD

**Issue by HarryCordewener** [pennmush/pennmush#1285]
**Test**: 
`th wshtml(ansi(hr,test),ansi(hr,test))`

**Result**:
`#-1 NESTED TAG`

While this remains the case, wshtml() isn't very useful for creating enhanced versions of say, poses etc. 
**Example**: `th wshtml(<span class="pose">%0</span>,%0)`

Is there a way to either have it keep the ansi, or change it to span like we already do for standard output to wshtml()?

**Comment by grapenut** [comment]
> wshtml() can't handle ansi
This is true. We talked online, but I thought I would update here for posterity.

If you want to nest ANSI strings within HTML in the web client you'll need to use tag()/tagwrap(). The wshtml() function encodes an ascii string into an HTML code fragment and sends it whole. If you use the Pueblo tag() and tagwrap() functions then the HTML tags are sent one by one in order with the ansi strings so we can keep track of the nested state and interleave the tags and parsed ANSI strings on the client.

**Comment by HarryCordewener** [comment]
Won't Fix. Intended behavior.
