### ISSUE TITLE
Two recent crashes

### ISSUE THREAD

**Issue by Balerion300** [pennmush/pennmush#1292]
After more than a month since our last update of Penn, and after what feels like years of stability, we've gotten two crashes in the span of about 12 hours. We have two core files from the crashes. I ran gdb and bt to get a stack trace, and they can be found here:

https://justpaste.it/2plr8
https://justpaste.it/39kxj

The common denominator seems to be sqlite.c between these. We use Mike/Talvo's mail system which uses a MySQL database for mail and bulletin board posts. I believe that's the only system we have which uses SQL at this time.

Here's our version info:

You are connected to Blood of Dragons
Address: http://www.westeros.org/BoD/
Last restarted: Mon Mar 11 03:04:44 2019
PennMUSH version 1.8.7 patchlevel 0 [08/10/2018]
Git revision: 576227e6
Build date: Sat Nov 10 14:05:24 CST 2018
Compiler: gcc -std=gnu99
Compilation flags: -g -O2 -pipe -march=native -Wall -Wextra -Wno-comment -Wno-char-subscripts -funsigned-char -Wa,--noexecstack -fstack-protector -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -I.. -I../hdrs -include ../config.h -include ../confmagic.h -include ../options.h -pthread  -D_FORTIFY_SOURCE=2 -I/usr/include -I/usr/include -I../pcre2/include     -I/usr/include/mysql -m64

**Comment by mike347** [comment]
This is a fairly old commit, might be worth updating.. there have been a few SQLite updates in the codebase since this commit, which may solve the issue above.

**Comment by grapenut** [comment]
Just interpreting those stack traces a bit... both crashes happen during an atr_iter_get(). One is iterating attributes during a dbck and the other is during a call to softcode function lattr().

**Comment by mrsenile** [comment]
Actually, double check where it's actually crashing.

it's crashing in the mutex lock on the memory allocation which is called inside an iter.

Without knowing the system I would verify there's enough physical memory to actually do the  malloc.  It sounds like it's potentially running out of resources.

**Comment by Balerion300** [comment]
Unfortunately, both times it happened we weren't around and only found out some time after. What I can say is that normally there's at least a gig of RAM free on this particular server, which also hosts a website with Redis and Varnish caches in place. Maybe if there's a spot of heavy usage, memory might get  eaten up. I'll monitor it and see if I can see anything on that end.

**Comment by mrsenile** [comment]
Check your /var/log/messages and/or /var/log/syslog and see if you may also notice some OOM messages or other notices of crashing.  It will help nail down if you're having memory consumption issues.

**Comment by grapenut** [comment]
> Actually, double check where it's actually crashing.
> 
> it's crashing in the mutex lock on the memory allocation which is called inside an iter.

It is not inside an iter... both crashes are happening downstream from atr_iter_get() when it calls sqlite3_mprintf() to store the attribute name query string.  One crash was during a dbck and the other while parsing the lattr() softcode function.

I agree that it seems like a memory allocation problem.

**Comment by Balerion300** [comment]
After some digging, heroic sysadmin thinks the issue was our nameserver that, after a security update, was leaking memory and then for whatever reason the MUSH was the one on the chopping block when OOM came along. 

She has fixed that issue and we'll keep an eye on it.
