### ISSUE TITLE
Adding support for a JSON flatfile

### ISSUE THREAD

**Issue by shawnw** [pennmush/pennmush#1295]
Thinking about a way to dump and read a JSON flatfile in addition to the current format.

Pros:

* It'd combine the game, chat and mail files all in one file, making backups easier and making it harder for them to get out of sync.
* Using a standard format opens up the possibility of using existing tools on it; the classic "Remove God's password because nobody can remember it" use case is likely a `jq` one-liner instead of having to compile and run a custom program like now.

Cons:

* When I get around to using sqlite for the backing store for the database, flatfiles become much less important, and SQL becomes the natural format for them - backing up to plain text and restoring becomes as simple as `sqlite3 -batch game.db .dump > backup.sql` and `sqlite3 newgame.db < backup.sql`. Would it be worth the effort?

**Comment by HarryCordewener** [comment]
What are the reliability, security, and read-speed implications?

**Comment by grapenut** [comment]
I'd say the pros for a JSON format are also pros for the SQLite3 format. Since moving to SQLite3 is the ultimate goal, I don't see a big benefit for going to JSON in the interim.

**Comment by talvo** [comment]
The first "pro" is an insanely minor one; we can already do this for PANIC dumps, and tbh I'm not sure why we don't just do it for all dumps already now...

Plus the existing flatfile format is, while not a standard format, still very easy to read and manipulate, and we have tools in place for the only common use-case of needing to hand-edit it.

Very little gain, IMHO, for a moderate amount of work and more hoops to jump through when moving a db between versions of Penn.

**Comment by shawnw** [comment]
Yeah, not worth the effort.
