### ISSUE TITLE
help queue2 doesn't exist

### ISSUE THREAD

**Issue by RedFinn** [pennmush/pennmush#1303]
"help queue2" returns the following: "No HELP entry for 'queue2'. Did you mean 'QUEUE3'?"

Is there a missing file, or should queue3 be queue2?

**Comment by ray73864** [comment]
Removal of 'queue2' from the helpfile was done on commit: https://github.com/pennmush/pennmush/commit/0864eb09096a0814a99f5a613a9d5ea1cc117abb#diff-4b91a5f77b78d1aaf089a8a7a202af66

... By Walker.

This was during Walker's rewrite of the queue.

**Comment by RedFinn** [comment]
Because of course it was Walker

**Comment by RedFinn** [comment]
It looks like the contents of QUEUE2 got consolidated with QUEUE, and Walker simply forgot to renumber.
