### ISSUE TITLE
Temperarly Pause and Unpause data going to our display

### ISSUE THREAD

**Issue by Eckspert** [pennmush/pennmush#1320]
I was just thinking, having a command to pause all text being received (Except from Wizards and things you control) would be helpful for us coders.. or just to take a break but not disconnect. I know this is what @lock/interact can do, I was thinking more on the whole game level. It gets very confusing when trying to debug massive code, and receiving messages in the middle of the debug.

**Comment by mrsenile** [comment]
Don't see a reason for this.  Clients allow buffering and recall as well as search-for in recall history.  Even Tinyfugue, considered one of the oldest clients in existance, offers this functionality.

**Comment by mike347** [comment]
Agreed. I don't see a real need for this. Going to close this as a 'Wont-implement' type deal.
