### ISSUE TITLE
Totcmds()

### ISSUE THREAD

**Issue by Eckspert** [pennmush/pennmush#1323]
This is a suggestion for a total cmd count since creation... to run along side of cmds() for each session.

**Comment by mike347** [comment]
This can easily be implemented with the event system, see 'help events':
`&PLAYER`DISCONNECT Event handler=&TOTAL_CMDS %0=[add(xget(%0,TOTAL_CMDS),last(%8,{/}))]`
IMO, not worth implementing in hard code.

**Comment by mrsenile** [comment]
totcmds() does a bit different in Rhost.

While it does pull the total commands from the above, it also adds the total commands of every session connected to the totals.

Granted, it could still be coded with the above to something like:

[ladd([get(%0/total_cmds)] [iter(lports(%0),cmds(%0,%i0))])]

I think that'd work.

**Comment by talvo** [comment]
As above; I don't think it's of much use generally, and can easily be softcoded for the few who do care.
