### ISSUE TITLE
Channel Mogrifier 

### ISSUE THREAD

**Issue by Eckspert** [pennmush/pennmush#1330]
The channel mogrifier arguments do not pass down through ufun

**Comment by mike347** [comment]
Can you elaborate?

**Comment by Eckspert** [comment]
&MOGRIFY`format #338=<%1> [ufun(pose`hug)]
&pose`hug #338=%0/%1/%2/%3/%4/%5/%6/%7

>> +p Hug
I see: <Public> ///////

**Comment by mike347** [comment]
You.. have to pass the parameters to the ufun().

**Comment by Eckspert** [comment]
This is different than the standard behavior. Usually such arguments will auto propogate down the chain.

**Comment by mike347** [comment]
`&MOGRIFYformat #338=<%1> [ufun(posehug,%0,%1,%2,%3,%4,%5,%6,%7)]`

**Comment by mike347** [comment]
Arguments do not automatically propagate, no. Q-regs do, but not arguments.
