### ISSUE TITLE
New Install/build.

### ISSUE THREAD

**Issue by dbmical** [pennmush/pennmush#1349]
I have been away from the coding scene for several years now.  I am building a new linux box, and putting pennmush on it, but getting this message:

myssl.c: In function  Ç get_dh2048 Ç :                                                                                  myssl.c:447:5: error: dereferencing pointer to incomplete type                                                             dh->p = BN_bin2bn(dh2048_p, sizeof(dh2048_p), NULL);                                                                      ^                                                                                                                  myssl.c:448:10: error: dereferencing pointer to incomplete type                                                            if (!dh->p) {                                                                                                                  ^                                                                                                             myssl.c:456:5: error: dereferencing pointer to incomplete type                                                             dh->g = BN_bin2bn(dh2048_g, sizeof(dh2048_g), NULL);                                                                      ^                                                                                                                  myssl.c:457:10: error: dereferencing pointer to incomplete type                                                            if (!dh->g) {                                                                                                                  ^                                                                                                             <builtin>: recipe for target 'myssl.o' failed                                                                           make[1]: *** [myssl.o] Error 1                                                                                          make[1]: Leaving directory '/home/doc/Land/src'                                                                         Makefile:41: recipe for target 'all' failed                                                                             make: *** [all] Error 2                               

I am pretty sure I am missing some libraries, but not sure what ones I'm missing.  There is no indication of missing libraries and the code looks right to me??

**Comment by talvo** [comment]
It depends on which flavour of Linux you're using, but most likely it's the ssl dev library you're missing (I believe it's usually named libssl-dev or some variation).

**Comment by dbmical** [comment]
Hummm...  I have that, and SEVERAL other libraries (non-conflicting, I checked) and still showing up..  Now to look at path to libraries I guess....

**Comment by dbmical** [comment]
Running Fedora 21 Server...

**Comment by dbmical** [comment]
Ok, had some issues with openSSL that needed fixed, and those are done, openSSL now is configured and set up correctly with the needed libraries, etc.  So it doesn't appear to be a openSSL issue on this end?

Any other ideas?

**Comment by shawnw** [comment]
I think we've seen this before and I thought it was fixed - something about changes in OpenSSL 1.1 that aren't backward compatible with 1.0 IIRC.

What version of OpenSSL does Fedora 21 have installed?

**Comment by dbmical** [comment]
Still having it, so i.must have an older version (although I did a get here two days before the initial message...)...

**Comment by dbmical** [comment]
openSSLopenSSL 1.1

**Comment by shawnw** [comment]
Hmm. Is `HAVE_DH_SET0_PQG` defined in your `config.h`?

**Comment by dbmical** [comment]
@shawnw That was it!  Thanks!

**Comment by shawnw** [comment]
Now to figure out why the configure script didn't catch that...

**Comment by dbmical** [comment]
That was my plan too!!  Looking into it...  (Like I said, it has been a while since I have coded anything of value...)

**Comment by dbmical** [comment]
I stand corrected.  Forgot to run "make update", it crashed at the same point over same issue after doing that and running "make install".

**Comment by shawnw** [comment]
Did you do something that would regenerate config.h? If that is defined, that block of code shouldn't be used in favor of an openssl 1.1-compatible one.

**Comment by dbmical** [comment]
I checked after running "make update" and that is still defined!?

**Comment by shawnw** [comment]
Still not working after changing config.h and it not being reset? Huh, that's really weird. I'll try to set up a Fedora 21 VM and see if  can replicate.

**Comment by dbmical** [comment]
Thanks!Dr. Donald M. BellCEO D&D Bell Enterprises, Inc954-688-3354www.ddbellenterprises.com
-------- Original message --------From: shawnw ***@***.***> Date: 3/10/21  15:01  (GMT-05:00) To: pennmush/pennmush ***@***.***> Cc: dbmical ***@***.***>, Author ***@***.***> Subject: Re: [pennmush/pennmush] New Install/build. (#1349) 
Still not working after changing config.h and it not being reset? Huh, that's really weird. I'll try to set up a Fedora 21 VM and see if  can replicate.

**Comment by dbmical** [comment]
Ok Shawnw.  I have the issue resolved.  I have taken my code that was running, updated them to run on Server 33, stepped my server up to 33, and it is now pennmush is now installing!!

Thank you for your time!
