### ISSUE TITLE
[Possible bug] Included PCRE preference over the installed one and proposed solution

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1355]
I think it may be a bug in Pennmush that it prefers and compiles the included PCRE library, even if in the system may be already one installed (it may be even a newer version of it then the included one).

My suggestion of solving it is that the ./configure would check the system if there is a PCRE already installed. If there would be none installed (or if it's an older version then the latest avaliable one) then, then it would download the latest version and compile it.

This way, Pennmush archive will reduce the size and would ensure to have the latest PCRE installed

**Comment by talvo** [comment]
As far as I'm aware (and I've not checked today, so my recollection may be wrong), Penn only downloads PCRE if configure didn't find a suitable version installed on the system. However, once you have a locally downloaded copy I think it will favour that if you re-run configure.

**Comment by toktoktheeo** [comment]
Hi, I can confirm that I have this issue related to pcre. I have a newer version installed on my system but configure still want to download pcre2-10.35. Furthermore, the ftp referenced in the configure file ( http://ftp.pcre.org/pub/pcre/ ) no longer exist. From pcre.org : "Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead."

**Comment by JayEeSea** [comment]
Is there some kind of work around for this?

**Comment by mike347** [comment]
Does your system have wget?

**Comment by shawnw** [comment]
I started out using a local copy of pcre2 because many OSes at the time didn't have a recent enough version to support features. And it's slightly customized by by the install script, so now a stock version won't work even if it's recent enough. I'll try to do a PR to fix the download link this weekend.

**Comment by mdziczkowski** [comment]
@JayEeSea I think that there need to be done changes in the code. Whenever I find some free time, I look thru the code and see if I can find something. Maybe @talvo or @shawnw could help to find a workaround ;-)

@mike347 I have both: wget and curl installed in their newest avaliable for my system versions

@shawnw I think that a good way to prevent in future similiar issues with the versions would be if there is a code implemented that would open the download link and check in it what is the newest version avaliable on it and then to compare that with the version with is installed. When a newer one is found on the server then download (eventually build it from the sources if avaliable) and install it.

On the side, I had experimented some with the programming enviroment settings and had discovered, that the best compilation results (optimized for speed and small size) are following compiler flags set:

> export CFLAGS='-O3 -Os -pipe'
> export CPPFLAGS=${CFLAGS}
> export CXXFLAGS=${CFLAGS}
> export GFLAGS=${CFLAGS}
> export GPPFLAGS=${CFLAGS}
> export GCCFLAGS=${CFLAGS}
> export GXXFLAGS=${CFLAGS}

**Comment by mike347** [comment]
@shawnw I put up a PR that is a temporary fix to this using wget to download from the new location. It works locally, fails in travis. 
https://github.com/pennmush/pennmush/pull/1376

**Comment by JayEeSea** [comment]
I ran into that same error in Travis but modified the Makefile to change the reference from pcre2-10.35 to pcre2-10.39 after making the mods to the configure and configure.in files and it compiled with no issues.

**Comment by shawnw** [comment]
I think curl is probably a better (Read: more likely to be installed on more servers) option than wget. I went with a core perl module to do the downloading because I *knew* perl was definitely going to be installed, but IIRC it doesn't support https without additional non-core modules (I don't know if there's a non-https download option on pcre.org), hence the http URL.
