### ISSUE TITLE
[Question + Feature request] Supported protocols

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1361]
I wanted to ask, if Pennmush does support following protocol's:

Bellow, I list most of them for you with the links and bellow the list I'll put the links to their description and definitions to provide informations for future implementation.

===== List ====

- MTTS (Mud Terminal Type Standard)
- MSLP (Mud Server Link Protocol)
- MSDP (Mud Server Data Protocol)
- MNES (MUD NEW-ENVIRON Standard)
- MMCP (Mud Master Chat Protocol)
- MCCP (Mud Client Compression Protocol)
- GMCP (Generic Mud Communication Protocol)
- EOR (End of Record)
- MCP (MUD Client Protocol)
- MSSP (Mud Server Status Protocol)
- MXP (MUD eXtension Protocol)
- MSP (MUD Sound Protocol)
- ZMP (Zenith MUD Protocol)

== Technical links ==

- [http://discworld.starturtle.net/external/protocols/zmp.htm](ZMP)
- [https://www.zuggsoft.com/zmud/msp.html](MSP)
- [http://www.zuggsoft.com/zmud/mxp.html](MXP)
- [https://tintin.mudhalla.net/protocols/mccp/](MCCP)
- [https://tintin.mudhalla.net/protocols/eor/](EOR)
- [https://www.moo.mud.org/mcp/](MCP)
- [https://tintin.mudhalla.net/protocols/gmcp/](GMCP)
- [https://tintin.mudhalla.net/protocols/mmcp/](MMCP)
- [https://tintin.mudhalla.net/protocols/mnes/](MNES)
- [https://tintin.mudhalla.net/protocols/msdp/](MSDP)
- [https://tintin.mudhalla.net/protocols/mslp/](MSLP)
- [https://tintin.mudhalla.net/protocols/mssp/](MMSP)
- [https://tintin.mudhalla.net/protocols/mtts/](MTTS)
- [https://tintin.mudhalla.net/protocols/mccp/](MCCP)
- [https://tintin.mudhalla.net/protocols/mssp/](MSSP)

My feature request is to attempt to implement the support of above protocols in the future versions of Pennmush.

Above feature request is motivated with the facts, that none of existing MUD/MUSH server does not have support of all of above (they have only support for sone of them implemented). Implementing the mentioned protocols would help Pennmush to become one of the most advanced and developed MUD/MUSH server.

It would be also a good idea to make:
- a code (in a separare source files, like for example: protocols), in with would be a "protocol manager", with would allow (and make easier) in the future versions to include the support of additional protocol
- separate folder with the protocol named sub-folders, in with would be the source files of the protocols. This would help to organize the code more and make the development lighter

**Comment by HarryCordewener** [comment]
PennMUSH has WebSocket, MSSP and Pueblo. I do not believe it has any of the other ones implemented. 
The developers are aware of these protocols, but have not implemented them. 
You'd need to come up with a pretty good reason for each individual protocol to get implemented into PennMUSH while understanding the actual environment and use-cases of MUSHes vs MUDs.

The only good callout here is that MXP does Pueblo better, and is actually supported. But again, this would take significant dev work.

**Comment by mdziczkowski** [comment]
if there would be the proposed protocol manager and "protocol template" created, then it would be easier to implement new protocols in an shorter time, without a loot of dev work (community could help then in the work to help the dev's to get bit less work)

**Comment by HarryCordewener** [comment]
There is no such thing as 'without a lot of dev work', that is not how programming works. This is an older C based codebase, with a very small base of actual maintainers. You are welcome to submit Pull Requests yourself if you manage to do this work.

**Comment by mdziczkowski** [comment]
I could attempt to do some code work, but I would need to have a "handler" (pice of code with would be something like an API (something like an driver) that would provide functions with would, along other load the protocol from a code I would write and implement it into Pennmush)

**Comment by tkrajcar** [comment]
A protocol's existence does not merit its implementation in PennMUSH. 

If a protocol:

* adds something notable and useful for the kind of audiences catered to by PennMUSH (which is quite different than a MUD audience),
* is in active use/demand by the community,
* has reasonably widespread client support
* aligns with the future roadmap/development plans for PennMUSH (which, for example, Pubelo does not)

then I would think it would make sense to add support for it. I'm quite confident that none of these meet that bar or it's quite likely they would have been implemented by now.

Anyone who feels sufficiently motivated is welcome to PR support for any new protocol and we'll definitely review it, but I would suggest the rubric above should be applied when considering those contributions, whether by the core team or by a community PR.

**Comment by talvo** [comment]
Rather than a list of a dozen protocols I'd suggest a ticket for the individual ones and a reason why you think that particular protocol is likely to be useful in Penn. If nothing else, a ticket with such a broad scope is all but impossible to action as no one has the time required to implement all of these at once (and likely not the interest in them all).

There is already a structure (if not quite an API) in place for adding new telnet protocols, if you wanted to do so; look at `init_telnet_opts` in bsd.c

**Comment by mdziczkowski** [comment]
I give some examples, of why some protocols were good to implement:

Many of present clients, like for example [https://wiki.mudlet.org](Mudlet), have already a build-in support for such protocols as GMCP, MSDP, MSSP and MSP. However, what could be made use of them if the server does not support most of them.

-The MCCP could reduce the used bandwidth for the communication between the server and user. It would increase the speed of connection and data transfer, with would be profitable for users with a weaker or slower internet connection and would allow them to enjoy the game with a good speed, without any lags

- The MMCP could allow to implement a chat-like functionality between the user into the server. Actually, Penn have some settings for the chat implemented, but I'm not sure if there is actually an usage of it done

- GMCP would take over and be responsible for the events related to the: connection, login, keep alive, etc. like events

- MSDP would take over and be responsible for the communication between the user and server related to the game itself (world, commands, etc.)

- MXP would handle better then Pubelo the HTML, etc. like content - Pubelo is a very limited and poor imitation ox MXP)

**Comment by talvo** [comment]
GMCP is already supported :) MSDP seems to just be another approach to the same thing?

MMCP is not particularly desirable, to me; previous solutions to solve a similar problem proved to be often-abused

MCCP is a huge amount of work to implement for a relatively little gain, given the amount of data being sent and modern internet connections. The benefit doesn't outweigh the time cost.

MXP is also a huge amount of work for relatively small gain due to limited client support. Not saying it will never happen, but it's not something that is likely to happen any time soon unless someone submits a patch.

**Comment by mdziczkowski** [comment]
It would be easier to help if there was a good documentation (except doxygen, with need to be re-configured and re-made anyway, because it shows only the source and header files, but does not show the else ones, like for example databases, configurations, etc.)

**Comment by annelions** [comment]
Just as a point of interest, people have been wanting Unicode for years. But that's going to require a rewrite of (most of) Penn, if it ever gets implemented. I would think that Unicode would be implemented before imperfectly-supported protocols that don't add much in the way of functionality to a Penn server.

**Comment by mdziczkowski** [comment]
if you want then I could include the edited `Doxygen` file with would generate the doxygen documentation for everything (plus, it's provide a missing on the existing [https://doxygen.pennmush.org/](doxygen documentation page) search, with making finding things in the documentation easier ;-) )

**Comment by HarryCordewener** [comment]
http://doxygen.pennmush.org/

**Comment by mdziczkowski** [comment]
@HarryCordewener I know that address and I refered myself to it ;-)

in my previous message I even tryed to paste it, but unstead of the link it showed it's code...

**Comment by annelions** [comment]
As a point of interest, I would like to say that perhaps Rhost would be better for your needs. Rhost does have an API that you could use to implement all these protocols with if you felt your game needed them.

**Comment by mdziczkowski** [comment]
@annelions not sure how it's by the version 4.0 of it, but the earlier one was based on an old version of Tiny (2.2), when there is already a version newer then 3.0
