### ISSUE TITLE
[Feature request] Global administrative interface

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1363]
I have a idea about solving some connected with each other issues.

How about create a interface with would allow to do the all tasks with are related to managemet of the server (settings, log  view and management, user management, security, updates, etc.)

This would allow to partially solve some problems with may occur in this topic.

**Comment by HarryCordewener** [comment]
PennMUSH has both API support and the ability for you to connect to a Wizard using a bot. 
Almost everything you have mentioned is something Wizards can already look at, and you can use standard Linux features to look at settings, logs, etc. Almost all of these things can be done using Softcode at this time.

You are welcome to develop this on your own time using the provided Softcode within the MUSH. But you are coming at this from the POV of this being a MUD it would seem. This is not how PennMUSH functions.

**Comment by mdziczkowski** [comment]
I meant more a console or graphical interface

**Comment by HarryCordewener** [comment]
You are welcome to try and make one and submit it as a Feature Request. But at this time, I do not believe any developer will spend time on such a request.

**Comment by talvo** [comment]
You can do pretty much everything from inside the MUSH with a wizard character. For changes at the terminal, there's no built-in interface, it does require editing the appropriate files to update config options and other things. While it would be possible to create an interface, it's a relatively big time investment for a relatively small gain, so unfortunately as Merc said it's not something which is likely to be done by one of the devs, I'm afraid.

**Comment by mdziczkowski** [comment]
@talvo Wouldn't be nice to have all administrative/wizard-like stuff into one place with would give an interface with all commands required for doing their (God/Wiz, etc.) tasks, without need to get known all commands? It could be helpful for less experienced administrators and those who are starting their adventure with Penn server and game administration in it

**Comment by MrWigggles** [comment]
Maybe? In some respects, yea, I can see a GUI being useful as GUI are
useful but at the end of the day, Penn is text driven and you need to use
text commands.
But I dont see a path to making it a general case GUI. I can see making a
specific case for Digging. Though only if you didnt want to do anything
fancy with exits. I also dont see how a GUI would help with a Room Parent
or Exit Parent... or any Parent. Thats how you really customize the room
through Parents.
It feels like you're trying to solve a lot of not problems and it feels
like you're inexperienced with Penn and Mushes. I'm glad you're enthused
and engaged. Thats great. But it feels like you havent Staffed and you have
made a grid.

I am giving it serious thought, and I dont see what wizard commands would
be useful as a GUI. Like a lot of Staff Commands are for games made for
that game.

Your goal is to make it more intuitive to someone new coming to the game,
and Mike and I have taken stabs at that. Though its hard to know how well
thats worked without feedback. I did a draft and Mike polish the newbie
guide in the helpfiles.
@talvo Can we set a default description to Room Zero?
Like we can write a primer in the Room Zero description. That explains Room
Zero, God, and the Masteroom. And point to the newbie helpful and the
helpfile in general?

**Comment by MrWigggles** [comment]
On Default Description, we can write one in the Description on God and one
for the Masteroom explaining Global Commands and Global Exits.
Oh, and we can point them toward M*U*S*H for further help.

**Comment by tkrajcar** [comment]
> @talvo Can we set a default description to Room Zero? Like we can write a primer in the Room Zero description. That explains Room Zero, God, and the Masteroom. And point to the newbie helpful and the helpfile in general?

The relevant code is at [db.c#2765](https://github.com/pennmush/pennmush/blob/41a3c01fdebd8b65654327f7bc41e1fc42f10ca6/src/db.c#L2765), feel free to make a PR.

**Comment by talvo** [comment]
> 
> 
> > @talvo Can we set a default description to Room Zero? Like we can write a primer in the Room Zero description. That explains Room Zero, God, and the Masteroom. And point to the newbie helpful and the helpfile in general?
> 
> The relevant code is at [db.c#2765](https://github.com/pennmush/pennmush/blob/41a3c01fdebd8b65654327f7bc41e1fc42f10ca6/src/db.c#L2765), feel free to make a PR.

Discussion on MUSH suggested having this information in a helpfile and simply pointing to it from Room Zero, so it's not lost when you set your own description. I like this idea. The default description could also then use textfile() to display it in the room desc. This would give the best of both worlds and make it considerably easier than hardcoding the text into db.c.

**Comment by talvo** [comment]
> 
> 
> @talvo Wouldn't be nice to have all administrative/wizard-like stuff into one place with would give an interface with all commands required for doing their (God/Wiz, etc.) tasks, without need to get known all commands? It could be helpful for less experienced administrators and those who are starting their adventure with Penn server and game administration in it

An actual GUI is 100% not practical.

A command-line interface is a little more practical but still an unrealistic amount of work for relatively little game; it would let people who have never touched a MUSH get one up and running more easily, but you can't actually _run_ a MUSH without learning most of these commands and how to get around inside the game. It's also far more practical to actually manage it from inside the game than having to log into the shell every time you want to do anything. There are also way too many commands to make a single interface outside the MUSH useful (you reach a point where you're effectively just duplicating all the existing commands; now when something changes you have two things, written in different languages, which need updating, someone will still have to learn what all the functionality is to use the interface, but now they're unable to do anything without shell access).

There is a learning curve to running a MUSH (and more so to building one from scratch); while this could be part of a solution to that, I don't think it's the best one. Ideally we could use some more up-to-date guides on developing a MUSH, but it's largely just a matter of sitting down and taking the time to read it all and learn.

**Comment by mdziczkowski** [comment]
@MrWigggles 

you had seen correctly my goal... to make the game (and administration) more intuitive for both, the players and the member of Staff (God, Wiz, Roy, etc.). It would help the both sides to enjoy more the Penn.

In my opinion, Penn has an great potential and with so many people who work hard to make it better (who's work I appreciate much), it can become someday fully unleashed ;-)

> Though its hard to know how well  thats worked without feedback

I haven't wroten that it need to become implemented immediatelly, but I meant it to put the new features step wlise, allowing it to pass the testing phases to see how would it work and get feedback on it

> @talvo Can we set a default description to Room Zero?
> Like we can write a primer in the Room Zero description. That explains Room
> Zero, God, and the Masteroom. And point to the newbie helpful and the
> helpfile in general?

How about naming the Room Zero as simple as "World", with the description starting from something like (for example): "You are somewhere in the world.".

Instead of setting any specific location (example: town, city, etc.), setting it to proposed "world" would give more freedom in the world creation

As for the Master room... I don't think it's a good name because it kinda assiocates with slavers and slaves ;-p

@talvo 

I meant a text-based GUI and not graphical one ;-p

**Comment by ray73864** [comment]
> @MrWigggles
> 
> you had seen correctly my goal... to make the game (and administration) more intuitive for both, the players and the member of Staff (God, Wiz, Roy, etc.). It would help the both sides to enjoy more the Penn.
> 
> In my opinion, Penn has an great potential and with so many people who work hard to make it better (who's work I appreciate much), it can become someday fully unleashed ;-)
> 

A GUI itself would make it less intuitive, once you have learnt the commands, read 'help newbie', looked at the other helpfiles, Penn is pretty powerful, and if Penn doesn't suit what you want, there are other MUSH servers out there that do things slightly differently.

> How about naming the Room Zero as simple as "World", with the description starting from something like (for example): "You are somewhere in the world.".
> 
> Instead of setting any specific location (example: town, city, etc.), setting it to proposed "world" would give more freedom in the world creation
> 

That would be horrible...

'World' doesn't convey anything at all, at least as 'Room Zero' it tells you that it is a room.

What happens if your game is set in space, on a space barge transporting hazardous waste through the universe? It's not a 'world' then.

> As for the Master room... I don't think it's a good name because it kinda assiocates with slavers and slaves ;-p
>

Master room's name serves its title well, it's where objects get put so that their commands master over all other commands on the game.

I suppose it could be called 'Global Room', but that sounds just as silly.
 
> @talvo
> 
> I meant a text-based GUI and not graphical one ;-p

...

When you connect to your game using a mushclient (Like Potato, MUSHClient, SimpleMU, BeipMU, Atlantis, etc...) you are connecting to a 'text-based GUI'.

Sure it isn't some of the fancy guis you might find in linux for managing stuff, but that would just add overhead and complexity, and starts becoming the realm of the MUD.

**Comment by talvo** [comment]
'GUI' literally stands for 'graphical user interface' :) 

While an external command-line interface for management would certainly be possible - most MUDs work this way - it's a very specific and deliberate design feature of MUSHes that this isn't needed, because the whole thing can be configured and built and recoded, by anyone, while it's up and running.

Honestly.. I see a lot of cost in building an interface and no gain. Your argument seems to be that you feel learning the commands is complex. The easiest solution? Softcode yourself an interface! You can install it in any game, it can be expanded with as many features as you want or customised easily, there's no real duplication at the basic level (since it will use the existing commands, you're not reinventing the wheel), and it's using decades-tested code under the hood with carefully-controlled permissions on who can do what.

As for renaming: The names make little difference; Room Zero is always renamed if it's actually used, it exists purely because the MUSH needs to have *something* that isn't the Master Room for other things (like God) to exist in. I'm perfectly happy with the name 'Master Room'.

**Comment by mdziczkowski** [comment]
> 'GUI' literally stands for 'graphical user interface' :)

yes, but it does not always need to mean one with windows, buttons, etc. ;-p

There are many text based GUI's, like for example a text mode installer of Linux, who is a GUI too because it gives a interface with interract with a user

> While an external command-line interface for management would certainly be possible - most MUDs work this way - it's a very specific and deliberate design feature of MUSHes that this isn't needed, because the whole thing can be configured and built and recoded, by anyone, while it's up and running.

I understand that, but focusing itself only on a limited text-based technology from early XX century, with has almost reached it's limit, will cause in not long time that the development will get stuck in a dead point since leak of possibility of implement new things.

I think that the better path for Penn to go would be a rewrite of code and making that there is a as minimal as possible server (something like an wrapper) who would provide only the service and handle the requests and responses and the rest would be as extensions for it

**Comment by talvo** [comment]
You are basically talking about making a new MUSH server. You're welcome to do that; many people have done so or thought about doing so. You're even welcome to fork Penn for it (if you follow the licence). But reworking Penn from the ground up as part of this project is not something the current devs are interested in doing.

**Comment by ray73864** [comment]
> yes, but it does not always need to mean one with windows, buttons, etc. ;-p
> 
> There are many text based GUI's, like for example a text mode installer of Linux, who is a GUI too because it gives a interface with interract with a user

Those would be chUI's not GUI's :)

Character User Interface as opposed to Graphical User Interface.

A GUI by its very nature will have bling bling on it such as buttons, etc...

**Comment by mdziczkowski** [comment]
hehe, ok ;-) but more accurate would be TUI (Text UI) ;-p
