### ISSUE TITLE
Wacky Idea Discord Like @ Notification

### ISSUE THREAD

**Issue by MrWigggles** [pennmush/pennmush#1366]
This is a new feature.

Basically you @<name> someone in a channel and it sends a time stamp, the channel name and the channel message in an @mail to the person notified. A downside is that this be less useful if that that game didnt have channel history, but not entirely useless. And the reason why it imporant to that the channel is included, as its a continuation of a public conversation and not the start of a private conversation. The @mail is the only way I can think up readily that'll help alert the player they got notified. Though if this is hardcoded maybe a notification can be sent when they log on. Maybe the @mail aspect isnt needed. 

Could this be done in softcode?
Probably? You could probably @hook every channel in your game, or the channels you want notifications then yse RegExp to match against all character names or all the characters on that channel. And with @inline also sent the mail to the tagged person.

Though I it would cause the @hook to activate every time someone uses a channel, which for public channel would a lot.

**Comment by HarryCordewener** [comment]
I mean, we'd be better creating an actual Discord and shadowing the channels. I've got stuff like that running on my MUSH, it doesn't take very much to do - aside from creating a small little javascript bot. 

Right now, this can easily be done with a Mogrifier. We already have a mogrifier on `M*U*S*H` that responds to @-ing people.

**Comment by talvo** [comment]
I kind of like the idea, but I do think it can be quite easily done in softcode with a mogrifier and an aconnect in the Master Room, and is possibly more suited to softcode for the games that want it.

An untested softcode variant, hacked from the `@chatto` system on `M*U*S*H` - both objects require Wiz due to setting/clearing attributes on players

```
@@ Recommended: @attribute/access chat_mentions=wizard no_command no_inherit no_clone mortal_dark

&MOGS`CHATTO Mogrifier=cond(cand(regmatch(%2%3,v(mogs`chatto`regexp),- toname msg),namelist(%q<toname>)),%q<msg>,strmatch(%3,@@*),delete(%3,0,1))
&MOGS`CHATTO`PLAYERNAME Mogrifier=if(cand(regmatch(%2%3,v(mogs`chatto`regexp),- toname),setr(tonamelist,namelist(%q<toname>))),%5 (to [switch(%q<tonamelist>,%#,%o[switch(%o,them,selves,self)],name(%q<tonamelist>)[ulocal(mogs`chatto`notify,%q<tonamelist>,%#,%4,edit(%4,%b,___),secs())]))
&MOGS`CHATTO`REGEXP Mogrifier=^.@("[^"]+"|[^@]\S*) (.+)$

@@ %0 = speaker, %1 = mentioned, %2 = chan, %3 = safechan, %4 = timestamp
&mogs`chatto`notify Mogrifier=cond(hasflag(%1,connected),switch(cstatus(%2,%1),On,,nspemit(%1,>> [name(%0)](%0) just mentioned you on <%2>.)),attrib_set(%1,chat_mentions`%3,add(default(%1/chat_mentions`%3,0),1))[attrib_set(%1,chat_mentions`%3`last,%4)][if(hasattr(%1,chat_mentions`%3`first),,attrib_set(%1,chat_mentions`%3`first,%4))])

@aconnect Global Object=@wait 2={@if hasattr(%#,chat_mentions)=@nspemit %#=You were mentioned [switch(words(setr(0,lattr(%#/chat_mentions`*))),1,on [ufun(fun`chat_mention,%q0)],on the following channels:%r[iter(%q0,%t[ufun(fun`chat_mention,%i0)],,%r)])]}

&fun`chat_mention Global Object=edit(elements(%0,2,`),___,%b) [switch(get(%#/%i0),1,at [timefmt($a $d $b $H:$M:$S, get(%#/%i0`first))],%$0 times between [timefmt($a $d $b $H:$M:$S, get(%#/%i0`first))] and [timefmt($a $d $b $H:$M:$S, get(%#/%i0`last))])]

@adisconnect Global Object=@wipe %#/chat_mentions
```

**Comment by MrWigggles** [comment]
I totally forgot about chat mogs. That looks a lot cleaner then the psedo code that was in my head.
