### ISSUE TITLE
[Feature Request] Allow rooms to be dug with specific DBREFs

### ISSUE THREAD

**Issue by RedFinn** [pennmush/pennmush#1369]
Inspired by a question on M\*U\*S\*H earlier today about changing the type of a database object, I realized that it's possible to @create a THING and assign it a specific DBREF, but it's not possible @dig a ROOM and do the same thing. Hence if someone were to decide that a THING that they had created ought to be a ROOM, and for whatever reason wanted to retain the DBREF, they could @recycle the THING, @dig the ROOM with the correct DBREF, then import all the appropriate attributes. No idea how feasible this is, just thought it would be neat.

**Comment by HarryCordewener** [comment]
That literally exists.
Read `help dig()`.

**Comment by dig** [comment]
> Inspired by a question on M*U*S*H earlier today about changing the type of a database object, I realized that it's possible to @create a THING and assign it a specific DBREF, but it's not possible @dig a ROOM and do the same thing. Hence if someone were to decide that a THING that they had created ought to be a ROOM, and for whatever reason wanted to retain the DBREF, they could @recycle the THING, @dig the ROOM with the correct DBREF, then import all the appropriate attributes. No idea how feasible this is, just thought it would be neat.

huh?

**Comment by RedFinn** [comment]
> That literally exists.
> Read `help dig()`.
> Read `help @dig`.
> 
> Wizards and objects with the pick_dbref power can also specify the dbrefs of garbage objects to use when creating the room and the to and from exits.

D'oh. I can't believe I missed that.
