### ISSUE TITLE
[Bug report] Configure PCRE version issues

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1380]
### Required informations:

***OS***: Debian 10
***Pennmush version***: 1.8.x

###Problem description:

There is a issue with the checking of the version of PCRE2 in the configure file.

As is well known, the components, like PCRE2, etc. are updated quite oftenly and hard coding into files like the "configure" a static version is a very bads idea because it becomes very quickly outdated and manually changes of tt's version is meanless. Additionally, instead of checking the installed version of PCRE2 (and other components), Pennmush is attempting to download an old, oftenly not accessable version of this component, even if a never version of it is already installed.

Thereof, as solution I would like to propose to modiffy the scripts used to prepare the sources before compilation that they do as following:

1. check if the element is already installed (skipping the version part)
2. if point 1 is true then check what version is installed
3. if point 1 is false or the version from point 2 is older then the newest avaliable then download, extract, compile and install it

**Comment by suityou01** [comment]
This is failing for me in this way. 

```#7 243.6 configure: Configuring PCRE2
#7 243.6 checking for pcre2-10.33... not found
#7 243.6 checking for pcre2-10.33.tar.gz... not found
#7 243.6 configure: Trying to download from http://ftp.pcre.org/pub/pcre/pcre2-10.33.tar.gz
#7 265.5 Fetch failed! HTTP response: 599 [Internal Exception] at -e line 1.
#7 287.1 Command failed:  at -e line 1.
#7 308.2 Could not open socket to 'ftp.pcre.org', 'Connection refused' at -e line 1.
#7 308.2 configure: error: Unable to automatically fetch file. Download it manually and try again.
#7 ERROR: executor failed running [/bin/sh -c set -ex     && adduser --disabled-password --gecos '' mush     && mkdir -p /mush && chown mush.mush /mush     && su -c 'git clone https://github.com/pennmush/pennmush.git /mush' mush     && su -c 'cd /mush && git checkout ${pennmush_version}' mush     && su -c 'cd /mush         &&         CFLAGS=-Wno-pragmas         SENDMAIL=/usr/sbin/sendmail         ./configure             --enable-ssl_slave             --enable-nls             --with-pcre' mush     && su -c 'cd /mush         && make update all install         && make portmsg' mush     && su -c 'mv /mush/game /mush/game.original' mush]: exit code: 1
```

**Comment by mdziczkowski** [comment]
Including two pull requests: #1382 and #1383 containing temporary workaround for the PCRE2 check issue.

- TODO: Replace the statically assigned in tha configure and configure.in files PCRE2 version into a dynamically checked one

**Comment by shawnw** [comment]
Updated with some of the renamed variables as part of #1416 

I don't want to automatically detect and download a newer version because the downloading code actually modifies the pcre2 source; I'd prefer that be manually checked to be sure it still works with a newer version.
