### ISSUE TITLE
1.8.8p0: aliascnf.dst not copied to alias.cnf

### ISSUE THREAD

**Issue by elseways** [pennmush/pennmush#1387]
Setting up a new MUSH, I was confused by aliases like `l` for `look` not working, but a little poking around in files revealed that the process of making a new server didn't copy `aliascnf.dst` into a new `alias.cnf` file the way `mushcnf.dst` does. `namescnf.dst` and `restrictcnf.dst` might also need help here.

**Comment by ray73864** [comment]
I'm sure at one point this used to appear in a 'readme' or helpfile or something, but from the penn root directory (where you ran 'make' and 'make install'), if you run 

``` make update ```

It'll copy the .dst files to their respective .cnf files in the gamedir (alias.cnf, mush.cnf, etc...) if they don't exist, and if they do exist, it'll merge any changes.

When the devs update stuff in the gamedir, they generally do it to the .dst files, so ``` make update ``` will check those .dst files for any differences between the .cnf files, and any found, make the changes to the .cnf file (it won't alter changes you have made to the .cnf files).

**Comment by elseways** [comment]
Ah, you're right. It's in the INSTALL.md file - I just didn't see it there. Thanks for finding that!
