### ISSUE TITLE
netmush issue

### ISSUE THREAD

**Issue by mbalax** [pennmush/pennmush#1395]
Hi All

Just back to the ol' Mush after a few years away . . . made a new setup on an Ubuntu VM and added some old databases from my archive.

All fine until on ./restart I get the following message:

 `restart: 143: ./netmush Exec format error `

and am unable to connect to the game, because the game (netmush) of course isn't running.

any ideas?

**Comment by talvo** [comment]
Did you build the whole game on your new system (ie, running ./configure and make), or did you copy the whole thing pre-built over from another system?

**Comment by talvo** [comment]
No problem, easily done; glad it's working now :)
