### ISSUE TITLE
ANSI in MOTD

### ISSUE THREAD

**Issue by mbalax** [pennmush/pennmush#1396]
Hi there

When I code the MOTD using ANSI:

`%r[ansi(hy,Welcome, you are connected to the Mush)]`

It doesn't show up in color and I just see the raw code.

It works fine as an emote, however.

**Comment by mike347** [comment]
How are you setting it? In-game via @MOTD or in a file?

**Comment by mbalax** [comment]
OK, that's good to know, thank you!
