### ISSUE TITLE
GMCP/OOB messages leave extraneous character visible in client.

### ISSUE THREAD

**Issue by bengustafson84** [pennmush/pennmush#1407]
When receiving GMCP / OOB() messages, in the Mudlet client, an extraneous character 'ð' is received in the game client and not out of band.  This happens from any OOB() push.  This does not occur in Mudlet in other GMCP implementations and localized to PennMUSH.

**Comment by talvo** [comment]
Thanks Ben. The character is code 240, which is the 'subnegotiation end' (SE) code for Telnet. I can't see that an additional one is being generated by the code for oob(). A few questions:

1) Does Mudlet have any kind of packet debugger that lets you see the raw data (including non-printed codes like telnet escape codes) being received?

2) Does this occur in all uses of oob() - such as:

```
think oob(me, foo)
think oob(me, foo, "bar")
````

(... Actually, not the first one, as there's been a bug introduced where it doesn't work without a `<message>` argument - will pick that up too.)

If not, can you give an example which does reproduce it?

3) Has anyone using another GMCP-enabled client reported this, or is it specific to Mudlet?

**Comment by bengustafson84** [comment]
Each oob() I've received I've had this character pop in.  I know it doesn't render in MUSHclient, but I'm also not sure if MUSHclient can show UTF-8 character codes.

I do have a session playback from Mudlet that shows the GMCP coming in.  It's meant to be played back in the Mudlet client, but opening the .dat file and you can see the raw GMCP incoming data.  I also have a playback from GMCP from a DikuMUD where I do NOT see this extra character upon receiving GMCP.

In both files, the GMCP data is the last line of the file.

[OOB Logs.zip](https://github.com/pennmush/pennmush/files/12352313/OOB.Logs.zip)

**Comment by talvo** [comment]
Argh. OK, I think I've tracked this down, but I'm having trouble reproducing reliably as my local test game doesn't support unicode; I may need to get someone else to look at testing a fix...

**Comment by talvo** [comment]
Fixed in 118d24664b2785a9c4f0768dfa4bf8be5abe58b9
