### ISSUE TITLE
[Feature request] LISTEN_PARENT checks on ancestor_<obj>

### ISSUE THREAD

**Issue by depwl9992** [pennmush/pennmush#1421]
Currently, objects (specifically things) do not seem to register the configured ancestor_thing as their explicit parent, but all parent functionality exists. I don't know if this is intentional or not, and is somewhat beside the point, as conformat, descformat, and other parent attributes are evaluated anyway.

That said - listen patterns are not checked on the ancestor object, and it would be nice if they were as long as LISTEN_PARENT is set on the child.

### Non-working example:
```
THING ANCESTOR (#4376TOSX)
Type: THING Flags: OPAQUE STICKY SAFE HEAVY
Parent: *NOTHING*
LISTEN_REACT[#1579]: ^string_to_trigger:@pemit %#=Ancestor caught it and child will do stuff probably! In fact my name is [name(me)]!
Home: Parent Room(#5654)
Location: Parent Room(#5654)

some guy named Phil(#10087TOM^)
Type: THING Flags: OPAQUE MONITOR LISTEN_PARENT
Parent: *NOTHING*
Home: depwl9992's House
Location: depwl9992's House

@pemit Phil=string_to_trigger
>
```

### A working example:
```
THING ANCESTOR (#4376TOSX)
Type: THING Flags: OPAQUE STICKY SAFE HEAVY
Parent: *NOTHING*
LISTEN_REACT[#1579]: ^string_to_trigger:@pemit %#=Ancestor caught it and child will do stuff probably! In fact my name is [name(me)]!
Home: Parent Room(#5654)
Location: Parent Room(#5654)

some guy named Phil(#10087TOM^)
Type: THING Flags: OPAQUE MONITOR LISTEN_PARENT
Parent: THING ANCESTOR (#4376TOSX)
Home: depwl9992's House
Location: depwl9992's House

@pemit Phil=string_to_trigger
> Ancestor caught it and child will do stuff probably! In fact my name is some guy named Phil!
```

Yeah, it'd be easy enough to just parent the object to the ancestor_thing, but it seems a bit cumbersome for something that should be done automatically as ancestor attributes already partially evaluate on unparented objects (huh; actually, commands don't work either. No wonder I made the "UNPARENTED THINGS" wizard command with a bit of clickable Pueblo to @-parent them to the ancestor_thing).

**Comment by talvo** [comment]
> Currently, objects (specifically things) do not seem to register the configured ancestor_thing as their explicit parent, but all parent functionality exists. I don't know if this is intentional or not, and is somewhat beside the point, as conformat, descformat, and other parent attributes are evaluated anyway.
That is the exact point/intention of an ancestor - it acts as a "final"/toplevel parent for all objects of that type without you having to actually explicitly \@parent.

The performance hit of having an ancestor checked for $-commands and ^-listens would be huge - it would essentially double the number of objects being checked every time. If you want ancestor-level checking for this, there's a good chance there's a better way to approach what you're trying to do (for example, instead of an ancestor $-command, you likely want a global $-command in the Master Room). What is the actual behaviour you want via an ancestor ^-listen?

**Comment by depwl9992** [comment]
I was more trying to replicate [this websocket handler for OpenAI](https://disloops.com/mush-gpt-the-oracle/) which uses a listen to catch the input text and execute a POST query up to a webserver.

I found an alternative way of handle it, though and found that parenting things to an "AI Handler" which had a local command was my best, most secure route for this specific project.

That said, other ideas could include some sort of language censor or bad word filter - something that could listen to @channels, says, poses or what-not semi-globally. This, I'm sure, could also be handled elsewhere also, possibly running all communication text through a filtering function.

In the end it just seems slightly odd that object ancestors aren't treated as true @parents. And it seems this is written in HELP ANCESTOR too. Yikes. My bad on missing that.

**Comment by talvo** [comment]
For filtering on \@channels, you want a mogrifier (help mogrifier). For other text, potentially an \@speechmod on the ancestor to filter at the point of speech (though obviously it can be overridden by someone setting one locally instead).
