### ISSUE TITLE
MUX style channel 'aliasses'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pennmush/pennmush#410]
```
Is this a command or @function?
Command

What will this do?
Emulate the MUX style of commands, where it simply does not require one to use 
'+' or otherwise before a channel's name to speak on it.
With other words:
pub Text | instead of | +pub text
Basically, removing the need for a prefix.

Can this be done in softcode?
Yes. But there's been so many wishes for this, it may be best to be added as a 
hardcode option.
```

Original issue reported on code.google.com by `ad...@twilightdays.org` on 1 Jan 2011 at 9:57

**Comment by talvo** [comment]
Updated patch for current PennMUSH (tbr as 1.8.6p0). Adds new functionality:
  `addcom <alias>=<channel>`
    Join `<channel>` if you aren't already on it, and add `<alias>` as an alias for `<channel>`.
  `<alias> WHO`
    Alias for @channel/who `<channel>`
  `<alias> OFF`
    Alias for @channel/gag `<channel>`
  `<alias> ON`
    Alias for @channel/ungag `<channel>`
  `delcom <alias>`
    Deletes the alias `<alias>` and, if it's the last alias you have for the matching channel, leave the channel.
  `@clist[/full]`
    List all channels. Alias of @channel/list. /full does nothing.
  `comtitle <alias>=<title>`
    Alias of @channel/title `<channel>`=`<title>`
  `comlist`
    Lists all aliases and their matching channels.
[muxcomm.txt](https://github.com/pennmush/pennmush/files/356271/muxcomm.txt)
