### ISSUE TITLE
@decompile/exclude obj/pattern

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pennmush/pennmush#635]
```
Exclude 'pattern' when decompiling an object.

Would be most useful for releasing only code on objects that store content.
```

Original issue reported on code.google.com by `delugeof...@gmail.com` on 20 Oct 2011 at 11:34

**Comment by talvo** [comment]
Not sure this is really practical. Consider using an \@parent instead for the shared code and a child for install-specific data.
