### ISSUE TITLE
New math functions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pennmush/pennmush#780]
```
These patches add the following new math functions, with documentation:

acosh()
acot()
acoth()
acsc()
acsch()
asec()
asinh()
asech()
atanh()
cosh()
cot()
coth()
csc()
csch()
sec()
sech()
sinh()
tanh()

```

Original issue reported on code.google.com by `Dawn.on....@gmail.com` on 20 Aug 2012 at 7:34

Attachments:
- [0001-Added-sinh.patch](https://storage.googleapis.com/google-code-attachments/pennmush/issue-780/comment-0/0001-Added-sinh.patch)
- [0002-Added-the-remaining-11-hyperbolic-and-inverse-hyperb.patch](https://storage.googleapis.com/google-code-attachments/pennmush/issue-780/comment-0/0002-Added-the-remaining-11-hyperbolic-and-inverse-hyperb.patch)
- [0003-Added-sec-csc-cot-asec-acsc-and-acot.patch](https://storage.googleapis.com/google-code-attachments/pennmush/issue-780/comment-0/0003-Added-sec-csc-cot-asec-acsc-and-acot.patch)
- [0004-Wrote-documentation.patch](https://storage.googleapis.com/google-code-attachments/pennmush/issue-780/comment-0/0004-Wrote-documentation.patch)

**Comment by shawnw** [comment]
Closing because we have a bazillion math functions already and these don't seem super useful. If somebody actually has a use for them, re-open and we can add them.

**Comment by talvo** [comment]
If there is serious interest in them, I'd rather see them go in as additional lmath() operators than as their own functions. But I'm not sure there is really enough use to be worth adding them at all.

**Comment by shawnw** [comment]
I think they all only work with a single argument, so lmath() doesn't make much sense.

**Comment by talvo** [comment]
Just plain math() then? ;) Just trying to avoid a ton of new functions.
