### ISSUE TITLE
Unread @mail notification on configurable interval

### ISSUE THREAD

**Issue by tkrajcar** [pennmush/pennmush#993]
I'd like to propose we add an unread @mail notification to connected players every <configurable-interval> seconds (0 to disable). It seems like one of those 'universally useful' features that many games have softcoded over the years.

**Comment by talvo** [comment]
The main problem with doing this is that it's usually not the /only/ thing you want in the notification (for instance, on M*U*S*H we also include your idle time and unread BB posts, among other things) and having them all separate, so they display at slightly different times, is annoying.

**Comment by tkrajcar** [comment]
Eh? I've never seen the M\*U\*S\*H notification you're talking about, ever, and frequently find I had unread mail from days ago that I didn't know about. I wonder why?

Anyway, to help address the sync issue, I would add an event handler that fires whenever the @mail check is run.
Thus, you can either:

1. Disable the built-in mailcheck and softcode your own on your own timer, as you can today
2. Synchronize any other checks/notifications you want to the @mail check - it'll be separate lines of output, but at least they're timed together.

**Comment by talvo** [comment]
+help +check for the M*U*S*H one :)

But, honestly, it's such a simple and basic thing to do that I think it becomes -more- complicated when you need to use the Event system and whatnot to hook into it and adjust the output than to just `@wait 3600=@pemit lwho()=Foo ; @trigger me/foo`

**Comment by tkrajcar** [comment]
After reviewing the +check on M\*U\*S\*H, it's actually quite different than what I'm talking about. It fires every hour no matter what, and is rather spammy. :stuck_out_tongue: 

What I was envisioning was something more along the lines of
```
GAME: You have 2 unread @mail messages.
```
that shows up every <configurable-interval-defaults-to-an-hour> - and only if you have unread @mail, if not, nothing is sent. 

If you wanted to check +bb at the same time, or do other such things, you could use the event handler to add on a message, so they'd be grouped together.

**Comment by HarryCordewener** [comment]
This can be done far too easily with a tiniest bit of softcode, as Talvo points out. Close this down!

**Comment by tkrajcar** [comment]
BAH FINE
