### ISSUE TITLE
Replace 'svninfo' in @version with git info

### ISSUE THREAD

**Issue by talvo** [pennmush/pennmush#994]
Make @version show git info where it previously showed svn info, if possible, or remove the svn-specific stuff if not.

**Comment by tkrajcar** [comment]
svn-specific stuff was removed by @shawnw in 69d4a7b14cfd2f81617ad44e6ffd13f5365ba817 already. I'll see about getting the git info in there.

**Comment by tkrajcar** [comment]
Man, if only @talvo would merge the PR I did to do his work for him... (Testing the notifier.)

**Comment by shawnw** [comment]
Also had gnu make isms and doesn't work right on other environments, though it does still build.

**Comment by shawnw** [comment]
Current version of this seems to be working fine on non-gnu systems.
